local _, br = ...
br.lists.spells.WARRIOR = br.lists.spells.WARRIOR or {}
br.lists.spells.WARRIOR.Shared = {
            abilities  = {
                attack              = 88163,
                battleShout         = 6673,
                battleStance        = 2457,
                berserkerRage       = 18499,
                berserkerStance     = 2458,
                charge              = 100,
                cleave              = 845,
                commandingShout     = 469,
                defensiveStance     = 71,
                demoralizingBanner  = 114203,
                disarm              = 676,
                execute             = 5308,
                hamstring           = 1715,
                heroicLeap          = 6544,
                heroicStrike        = 78,
                heroicThrow         = 57755,
                intervene           = 3411,
                intimidatingShout   = 5246,
                mockingBanner       = 114192,
                pummel              = 6552,
                rallyingCry         = 97462,
                recklessness        = 1719,
                -- shieldBlock   = 2565,
                -- shieldSlam    = 23922,
                shatteringThrow     = 64382,
                shieldWall          = 871,
                skullBanner         = 114207,
                spellReflection     = 23920,
                sunderArmor         = 7386,
                taunt               = 355,
                throw               = 122475,
                thunderClap         = 6343,
                victoryRush         = 34428,
                -- whirlwind     = 1680,
            },
            buffs      = {
                battleShout         = 6673,
                -- berserkerRage     = 18499,
                bloodbath           = 12292,
                defensiveStance     = 71,
                enrage              = 12880,
                -- firstStrike       = 325381,
                -- fujiedasFury      = 207776,
                -- ignorePain        = 190456,
                -- outburst          = 364010,
                recklessness        = 1719,
                -- seeingRed         = 364006,
                skullBanner         = 114207,
                -- smolderingInertia = 322032,
                -- spellReflection   = 23920,
                victorious          = 32216,
            },
            debuffs    = {
                deepWounds     = 115768,
                disarm         = 116095,
                -- markOfFyralath = 414532,
            },
            glyphs     = {

            },
            items      = {
                -- treacherousTransmitter = 221023,
            },
            talents    = {
                avatar               = 107574,
                bladestorm           = 46924,
                bloodbath            = 12292,
                doubleTime           = 103827,
                disruptingShout      = 102060,
                dragonRoar           = 118000,
                enragedRegeneration  = 55694,
                impendingVictory     = 103840,
                juggernaut           = 103826,
                massSpellReflection  = 114028,
                piercingHowl         = 12323,
                safeguard            = 114029,
                secondWind           = 29838,
                shockwave            = 46968,
                staggeringShout      = 107566,
                stormBolt            = 107570,
                vigilance            = 114030,
                warbringer           = 103828,
            },
        }
