local _, br = ...
br.lists.spells.PALADIN = br.lists.spells.PALADIN or {}
br.lists.spells.PALADIN.Shared = {
            abilities  = {
                arcaneTorrent        = 155145, --
                consecration         = 26573,  --
                crusaderAura         = 32223,  --
                crusaderStrike       = 35395,  --
                divineShield         = 642,    --
                flashOfLight         = 19750,  --
                hammerOfJustice      = 853,    --
                handOfReckoning      = 62124,  --
                intercession         = 391054, --
                judgment             = 20271,  --
                redemption           = 7328,   --
                retributionAura      = 183435, --
                senseUndead          = 5502,   --
                shieldOfTheRighteous = 53600,  --
                wordOfGlory          = 85673,  --
            },
            buffs      = {
                avengingWrath        = 31884,
                consecration         = 26573,
                concentrationAura    = 317920,
                crusaderAura         = 32223,
                devotionAura         = 465,
                divineResonance      = 384029,
                divineShield         = 642,
                divineSteed          = 221883,
                echoesOfWrath        = 423590,
                blessingOfProtection = 1022,
                holyAvenger          = 105809,
                retributionAura      = 183435,
                seraphim             = 152262,
                vanquishersHammer    = 328204,
            },
            debuffs    = {
                blindingLight   = 105421,
                forbearance     = 25771,
                hammerOfJustice = 853,
                judgment        = 197277,
                turnEvil        = 10326,
                handOfReckoning = 62124,
            },
            glyphs     = {
                glyphOfFireFromHeavens    = 57954,
                glyphOfPillarOfLight      = 146959,
                glyphOfTheLuminousCharger = 89401,
                glyphOfTheQueen           = 212642,
            },
            talents    = {
                afterimage                   = 385414, --
                aurasOfSwiftVengeance        = 385639, --
                aurasOfTheResolute           = 385633, --
                avengingWrath                = 31884,  --
                blessingOfFreedom            = 1044,   --
                blessingOfProtection         = 1022,   --
                blessingOfSacrifice          = 6940,   --
                blindingLight                = 115750, --
                cavalier                     = 230332, --
                cleanseToxins                = 213644, --
                crusadersReprieve            = 403042, --
                divinePurpose                = 408459, --
                divineResonance              = 384027, --
                divineSteed                  = 190784, --
                divineToll                   = 375576, --
                fadingLight                  = 405768, --
                faithsArmor                  = 406101, --
                fistOfJustice                = 234299, --
                goldenPath                   = 377128, --
                greaterJudgment              = 231663, --
                hammerOfWrath                = 24275,  --
                healingHands                 = 326734, --
                holyAegis                    = 385515, --
                improvedBlessingOfProtection = 384909, --
                incandescence                = 385464, --
                judgmentOfLight              = 183778, --
                justification                = 377043, --
                layOnHands                   = 633,    --
                lightforgedBlessing          = 403479, --
                obduracy                     = 385427, --
                ofDuskAndDawn                = 385125, --
                punishment                   = 403530, --
                quickenedInvocation          = 379391, --
                rebuke                       = 96231,  --
                recompense                   = 384914, --
                repentance                   = 20066,  --
                sacrificeOfTheJust           = 384820, --
                sanctifiedPlates             = 402964, --
                sealOfAlacrity               = 385425, --
                sealOfMercy                  = 384897, --
                sealOfMight                  = 385450, --
                sealOfOrder                  = 385129, --
                sealOfTheCrusader            = 385728, --
                seasonedWarhorse             = 376996, --
                strengthOfConviction         = 379008, --
                touchOfLight                 = 385349, --
                turnEvil                     = 10326,  --
                unboundFreedom               = 305394, --
                unbreakableSpirit            = 114154, --
                vengefulWrath                = 406835, --
            },
        }
