local _, br = ...
if br.lists == nil then br.lists = {} end

-- Generated by BreweryNav spell generator
-- Source build : 12.0.1.66384
-- Extracted at : 2026-03-26T09:58:38Z
-- DO NOT EDIT  — regenerate from BreweryNav.Extractor.SpellIds

br.lists.spells = {
    DEATHKNIGHT = {
        [250] = {
            abilities = {
                abominationLimb   = 1263569,
                bloodBoil         = 50842,
                consumption       = 1263824,
                dancingRuneWeapon = 49028,
                deathStrike       = 49998,
                deathsCaress      = 195292,
                heartStrike       = 206930,
                marrowrend        = 195182,
                reapersMark       = 439843,
            },
            buffs = {
                gorefiendsGrasp = 108199,
                vampiricBlood   = 55233,
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                abominationLimb   = 1263569,
                bloodBoil         = 50842,
                consumption       = 1263824,
                dancingRuneWeapon = 49028,
                deathStrike       = 49998,
                deathsCaress      = 195292,
                gorefiendsGrasp   = 108199,
                heartStrike       = 206930,
                marrowrend        = 195182,
                reapersMark       = 439843,
                vampiricBlood     = 55233,
            },
        },
        [251] = {
            abilities = {
                breathOfSindragosa = 1249658,
                empowerRuneWeapon  = 47568,
                frostStrike        = 49143,
                frostscythe        = 207230,
                frostwyrmsFury     = 279302,
                glacialAdvance     = 194913,
                howlingBlast       = 49184,
                obliterate         = 49020,
                reapersMark        = 439843,
                remorselessWinter  = 196770,
            },
            buffs = {
                iceboundFortitude = 48792,
                pillarOfFrost     = 51271,
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                breathOfSindragosa = 1249658,
                empowerRuneWeapon  = 47568,
                frostStrike        = 49143,
                frostscythe        = 207230,
                frostwyrmsFury     = 279302,
                glacialAdvance     = 194913,
                howlingBlast       = 49184,
                iceboundFortitude  = 48792,
                obliterate         = 49020,
                pillarOfFrost      = 51271,
                reapersMark        = 439843,
                remorselessWinter  = 196770,
            },
        },
        [252] = {
            abilities = {
                epidemic        = 207317,
                festeringStrike = 85948,
                outbreak        = 77575,
                putrefy         = 1247378,
                raiseDead       = 46584,
                raiseDead_46585 = 46585,
                scourgeStrike   = 55090,
                soulReaper      = 343294,
            },
            buffs = {
                armyOfTheDead      = 42650,
                darkTransformation = 1233448,
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                armyOfTheDead      = 42650,
                darkTransformation = 1233448,
                epidemic           = 207317,
                festeringStrike    = 85948,
                outbreak           = 77575,
                putrefy            = 1247378,
                raiseDead          = 46584,
                raiseDead_46585    = 46585,
                scourgeStrike      = 55090,
                soulReaper         = 343294,
            },
        },
        Shared = {
            abilities = {
                abominationLimb            = 315443,
                antiMagicZone              = 51052,
                chainsOfIce                = 45524,
                consumption                = 205223,
                consumption_205224         = 205224,
                deathCoil                  = 47541,
                deathGate                  = 50977,
                deathGrip                  = 49576,
                foulMenagerie              = 58723,
                frostBreath                = 190780,
                geist                      = 58707,
                mindFreeze                 = 47528,
                packHobgoblin              = 69046,
                raiseAlly                  = 61999,
                runeOfRazorice             = 53343,
                runeOfSanguination         = 326805,
                runeOfSpellwarding         = 326855,
                runeOfTheApocalypse        = 327082,
                runeOfTheFallenCrusader    = 53344,
                runeOfTheStoneskinGargoyle = 62158,
                runeOfUnendingThirst       = 326977,
                runeStrike                 = 316239,
                runeforging                = 53428,
                sindragosasFury            = 190778,
                skeleton                   = 147963,
                swarmingMist               = 311648,
                twoForms                   = 68996,
                wraithWalk                 = 212552,
            },
            buffs = {
                acherusDeathcharger       = 48778,
                antiMagicShell            = 48707,
                apocalypse                = 220143,
                arcaneTorrent             = 50613,
                blindingSleet             = 207167,
                calmTheWolf               = 406087,
                darkflight                = 68992,
                deathAndDecay             = 43265,
                deathPact                 = 48743,
                deathsAdvance             = 48265,
                giftOfTheNaaru            = 59545,
                lichborne                 = 49039,
                pathOfFrost               = 3714,
                wingedSteedOfTheEbonBlade = 54729,
            },
            debuffs = {
                asphyxiate         = 221562,
                bloodPlague        = 55078,
                controlUndead      = 111673,
                corpseExploder     = 127344,
                darkCommand        = 56222,
                frostFever         = 55095,
                shackleTheUnworthy = 312202,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                antiMagicZone = 51052,
                asphyxiate    = 221562,
                blindingSleet = 207167,
                controlUndead = 111673,
                deathPact     = 48743,
                mindFreeze    = 47528,
                wraithWalk    = 212552,
            },
        },
    },
    DEMONHUNTER = {
        [577] = {
            abilities = {
                chaosNova       = 179057,
                essenceBreak    = 258860,
                eyeBeam         = 198013,
                felblade        = 232893,
                vengefulRetreat = 198793,
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                chaosNova       = 179057,
                essenceBreak    = 258860,
                eyeBeam         = 198013,
                felblade        = 232893,
                vengefulRetreat = 198793,
            },
        },
        [581] = {
            abilities = {
                chaosNova      = 179057,
                felDevastation = 212084,
                felblade       = 232893,
                fieryBrand     = 204021,
                sigilOfChains  = 202138,
                sigilOfMisery  = 207684,
                sigilOfSilence = 202137,
                sigilOfSpite   = 390163,
                soulCarver     = 207407,
            },
            buffs = {
                spiritBomb = 247454,
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                chaosNova      = 179057,
                felDevastation = 212084,
                felblade       = 232893,
                fieryBrand     = 204021,
                sigilOfChains  = 202138,
                sigilOfMisery  = 207684,
                sigilOfSilence = 202137,
                sigilOfSpite   = 390163,
                soulCarver     = 207407,
                spiritBomb     = 247454,
            },
        },
        [1480] = {
            abilities = {
                blur              = 198589,
                consume           = 473662,
                shift             = 1234796,
                spectralSight     = 1251417,
                voidMetamorphosis = 1217605,
                voidNova          = 1234195,
                voidRay           = 473728,
                voidblade         = 1245412,
            },
            buffs = {
                reap           = 1226019,
                soulImmolation = 1241937,
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                blur              = 198589,
                consume           = 473662,
                reap              = 1226019,
                shift             = 1234796,
                soulImmolation    = 1241937,
                spectralSight     = 1251417,
                voidMetamorphosis = 1217605,
                voidNova          = 1234195,
                voidRay           = 473728,
                voidblade         = 1245412,
            },
        },
        Shared = {
            abilities = {
                activatingSpecialization = 200749,
                consumeMagic             = 278326,
                demonsBite               = 344859,
                disrupt                  = 183752,
                elysianDecree            = 306830,
                immolationAura           = 258920,
                sigilOfFlame             = 204596,
            },
            buffs = {
                arcaneTorrent = 202719,
                darkness      = 196718,
                felsaber      = 200175,
                groveDefiler  = 193007,
            },
            debuffs = {
                imprison    = 217832,
                sinfulBrand = 317009,
                torment     = 185245,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                consumeMagic = 278326,
                darkness     = 196718,
                imprison     = 217832,
            },
        },
    },
    DRUID = {
        [102] = {
            abilities = {
                forceOfNature    = 205636,
                newMoon          = 274281,
                removeCorruption = 2782,
                shapeshiftForm   = 228545,
                solarBeam        = 78675,
                starfire         = 194153,
                starsurge        = 78674,
                wildMushroom     = 88747,
                wrath            = 190984,
            },
            buffs = {
                convokeTheSpirits = 391528,
                moonkinForm       = 24858,
                starfall          = 191034,
            },
            debuffs = {
                furyOfElune = 202770,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                convokeTheSpirits = 391528,
                forceOfNature     = 205636,
                furyOfElune       = 202770,
                moonkinForm       = 24858,
                newMoon           = 274281,
                removeCorruption  = 2782,
                shapeshiftForm    = 228545,
                solarBeam         = 78675,
                starfall          = 191034,
                starfire          = 194153,
                starsurge         = 78674,
                wildMushroom      = 88747,
                wrath             = 190984,
            },
        },
        [103] = {
            abilities = {
                chomp                       = 1244258,
                incarnationAvatarOfAshamane = 102543,
                primalWrath                 = 285381,
                rake                        = 1822,
                removeCorruption            = 2782,
                skullBash                   = 106839,
                starfire                    = 197628,
                starsurge                   = 197626,
                swipe                       = 213764,
            },
            buffs = {
                convokeTheSpirits = 391528,
                feralFrenzy       = 274837,
                franticFrenzy     = 1243807,
                moonkinForm       = 197625,
                survivalInstincts = 61336,
                tigersFury        = 5217,
            },
            debuffs = {
                rip = 1079,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                chomp                       = 1244258,
                convokeTheSpirits           = 391528,
                feralFrenzy                 = 274837,
                franticFrenzy               = 1243807,
                incarnationAvatarOfAshamane = 102543,
                moonkinForm                 = 197625,
                primalWrath                 = 285381,
                rake                        = 1822,
                removeCorruption            = 2782,
                rip                         = 1079,
                skullBash                   = 106839,
                starfire                    = 197628,
                starsurge                   = 197626,
                survivalInstincts           = 61336,
                swipe                       = 213764,
                tigersFury                  = 5217,
            },
        },
        [104] = {
            abilities = {
                lunarBeam        = 204066,
                maul             = 6807,
                raze             = 400254,
                removeCorruption = 2782,
                skullBash        = 106839,
                starfire         = 197628,
                starsurge        = 197626,
                sunderingRoar    = 1253799,
                swipe            = 213764,
            },
            buffs = {
                berserk                    = 50334,
                bristlingFur               = 155835,
                convokeTheSpirits          = 391528,
                frenziedRegeneration       = 22842,
                incarnationGuardianOfUrsoc = 102558,
                moonkinForm                = 197625,
                survivalInstincts          = 61336,
            },
            debuffs = {
                redMoon = 1252871,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                berserk                    = 50334,
                bristlingFur               = 155835,
                convokeTheSpirits          = 391528,
                frenziedRegeneration       = 22842,
                incarnationGuardianOfUrsoc = 102558,
                lunarBeam                  = 204066,
                maul                       = 6807,
                moonkinForm                = 197625,
                raze                       = 400254,
                redMoon                    = 1252871,
                removeCorruption           = 2782,
                skullBash                  = 106839,
                starfire                   = 197628,
                starsurge                  = 197626,
                sunderingRoar              = 1253799,
                survivalInstincts          = 61336,
                swipe                      = 213764,
            },
        },
        [105] = {
            abilities = {
                efflorescence           = 145205,
                naturesCure             = 88423,
                removeCorruption        = 2782,
                removeCorruption_440015 = 440015,
                revitalize              = 212040,
                starfire                = 197628,
                starsurge               = 197626,
                swiftmend               = 18562,
                tranquility             = 740,
            },
            buffs = {
                convokeTheSpirits     = 391528,
                incarnationTreeOfLife = 33891,
                ironbark              = 102342,
                lifebloom             = 33763,
                naturesSwiftness      = 132158,
                rejuvenation          = 774,
                wildGrowth            = 48438,
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                convokeTheSpirits       = 391528,
                efflorescence           = 145205,
                incarnationTreeOfLife   = 33891,
                ironbark                = 102342,
                lifebloom               = 33763,
                naturesCure             = 88423,
                naturesSwiftness        = 132158,
                rejuvenation            = 774,
                removeCorruption        = 2782,
                removeCorruption_440015 = 440015,
                revitalize              = 212040,
                starfire                = 197628,
                starsurge               = 197626,
                swiftmend               = 18562,
                tranquility             = 740,
                wildGrowth              = 48438,
            },
        },
        Shared = {
            abilities = {
                adaptiveSwarm     = 325727,
                ferociousBite     = 22568,
                maim              = 22570,
                mangle            = 33917,
                markOfTheCheetah  = 131151,
                markOfTheOrca     = 54872,
                revive            = 50769,
                shred             = 5221,
                soothe            = 2908,
                theSun            = 171891,
                theUrsolChameleon = 58158,
                typhoon           = 132469,
                ursolsVortex      = 102793,
                yserasGift        = 145109,
                yserasGift_145110 = 145110,
            },
            buffs = {
                convokeTheSpirits     = 323764,
                flightForm            = 165962,
                heartOfTheWild        = 1261867,
                incapacitatingRoar    = 99,
                innervate             = 29166,
                ironfur               = 192081,
                kindredSpirits        = 326434,
                markOfTheWild         = 1126,
                ravenousFrenzy        = 323546,
                stampedingRoar        = 106898,
                sunfire               = 93402,
                symbioticRelationship = 474750,
                tigerDash             = 252216,
                wildCharge            = 102401,
            },
            debuffs = {
                cyclone          = 33786,
                growl            = 6795,
                hibernate        = 2637,
                massEntanglement = 102359,
                mightyBash       = 5211,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                cyclone               = 33786,
                heartOfTheWild        = 1261867,
                hibernate             = 2637,
                incapacitatingRoar    = 99,
                innervate             = 29166,
                ironfur               = 192081,
                maim                  = 22570,
                massEntanglement      = 102359,
                mightyBash            = 5211,
                soothe                = 2908,
                stampedingRoar        = 106898,
                sunfire               = 93402,
                symbioticRelationship = 474750,
                tigerDash             = 252216,
                typhoon               = 132469,
                ursolsVortex          = 102793,
                wildCharge            = 102401,
            },
        },
    },
    EVOKER = {
        [1467] = {
            abilities = {
                dragonrage = 375087,
                landslide  = 358385,
                pyre       = 357211,
                quell      = 351338,
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                eternitySurge = 359073,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                dragonrage    = 375087,
                eternitySurge = 359073,
                landslide     = 358385,
                pyre          = 357211,
                quell         = 351338,
            },
        },
        [1468] = {
            abilities = {
                echo            = 364343,
                expunge         = 365585,
                temporalAnomaly = 373861,
                verdantEmbrace  = 360995,
            },
            buffs = {
                dreamBreath  = 355936,
                dreamFlight  = 359816,
                reversion    = 366155,
                rewind       = 363534,
                stasis       = 370537,
                timeDilation = 357170,
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                dreamBreath     = 355936,
                dreamFlight     = 359816,
                echo            = 364343,
                expunge         = 365585,
                reversion       = 366155,
                rewind          = 363534,
                stasis          = 370537,
                temporalAnomaly = 373861,
                timeDilation    = 357170,
                verdantEmbrace  = 360995,
            },
        },
        [1473] = {
            abilities = {
                eruption   = 395160,
                landslide  = 358385,
                prescience = 409311,
                quell      = 351338,
            },
            buffs = {
                blisteringScales = 360827,
                breathOfEons     = 403631,
                ebonMight        = 395152,
                obsidianScales   = 363916,
                timeSkip         = 404977,
            },
            debuffs = {
                bestowWeyrnstone = 408233,
                timelessness     = 412710,
                upheaval         = 396286,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                bestowWeyrnstone = 408233,
                blisteringScales = 360827,
                breathOfEons     = 403631,
                ebonMight        = 395152,
                eruption         = 395160,
                landslide        = 358385,
                obsidianScales   = 363916,
                prescience       = 409311,
                quell            = 351338,
                timeSkip         = 404977,
                timelessness     = 412710,
                upheaval         = 396286,
            },
        },
        Shared = {
            abilities = {
                azureStrike         = 362969,
                blessingOfTheBronze = 364342,
                boonOfTheCovenants  = 387168,
                cauterizingFlame    = 374251,
                emeraldBlossom      = 355913,
                livingFlame         = 361469,
                return              = 361227,
                skywardAscent       = 376744,
                timeSpiral          = 374968,
                visage              = 351239,
            },
            buffs = {
                aerialHalt     = 403216,
                chosenIdentity = 360022,
                deepBreath     = 357210,
                fireBreath     = 357208,
                hover          = 358267,
                oppressingRoar = 372048,
                soar           = 369536,
                sourceOfMagic  = 369459,
                spatialParadox = 406732,
                surgeForward   = 376743,
                tailSwipe      = 368970,
                tipTheScales   = 370553,
                zephyr         = 374227,
            },
            debuffs = {
                disintegrate     = 356995,
                furyOfTheAspects = 390386,
                rescue           = 370665,
                sleepWalk        = 360806,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                cauterizingFlame = 374251,
                oppressingRoar   = 372048,
                rescue           = 370665,
                sleepWalk        = 360806,
                sourceOfMagic    = 369459,
                spatialParadox   = 406732,
                timeSpiral       = 374968,
                tipTheScales     = 370553,
                zephyr           = 374227,
            },
        },
    },
    HUNTER = {
        [253] = {
            abilities = {
                blackArrow   = 466930,
                cobraShot    = 193455,
                counterShot  = 147362,
                intimidation = 19577,
                killCommand  = 34026,
                wildThrash   = 1264359,
            },
            buffs = {
                bestialWrath         = 19574,
                eyesOfTheBeast       = 321297,
                survivalOfTheFittest = 264735,
            },
            debuffs = {
                barbedShot = 217200,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                barbedShot           = 217200,
                bestialWrath         = 19574,
                blackArrow           = 466930,
                cobraShot            = 193455,
                counterShot          = 147362,
                eyesOfTheBeast       = 321297,
                intimidation         = 19577,
                killCommand          = 34026,
                survivalOfTheFittest = 264735,
                wildThrash           = 1264359,
            },
        },
        [254] = {
            abilities = {
                aimedShot    = 19434,
                counterShot  = 147362,
                intimidation = 474421,
                killShot     = 53351,
                multiShot    = 257620,
            },
            buffs = {
                eagleEye             = 6197,
                survivalOfTheFittest = 264735,
                trueshot             = 288613,
                volley               = 260243,
            },
            debuffs = {
                harriersCry = 466904,
                rapidFire   = 257044,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                aimedShot            = 19434,
                counterShot          = 147362,
                eagleEye             = 6197,
                harriersCry          = 466904,
                intimidation         = 474421,
                killShot             = 53351,
                multiShot            = 257620,
                rapidFire            = 257044,
                survivalOfTheFittest = 264735,
                trueshot             = 288613,
                volley               = 260243,
            },
        },
        [255] = {
            abilities = {
                boomstick      = 1261193,
                flamefangPitch = 1251592,
                intimidation   = 19577,
                muzzle         = 187707,
                raptorStrike   = 186270,
                wildfireBomb   = 259495,
            },
            buffs = {
                killCommand          = 259489,
                survivalOfTheFittest = 264735,
                takedown             = 1250646,
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                boomstick            = 1261193,
                flamefangPitch       = 1251592,
                intimidation         = 19577,
                killCommand          = 259489,
                muzzle               = 187707,
                raptorStrike         = 186270,
                survivalOfTheFittest = 264735,
                takedown             = 1250646,
                wildfireBomb         = 259495,
            },
        },
        Shared = {
            abilities = {
                autoShot          = 75,
                bindingShot       = 109248,
                commandPet        = 272651,
                deathChakram      = 325028,
                flayedShot        = 324149,
                lesserProportion  = 58188,
                resonatingArrow   = 308491,
                tarTrap           = 187698,
                tranquilizingShot = 19801,
                wildSpirits       = 328231,
            },
            buffs = {
                arcaneTorrent   = 80483,
                camouflage      = 199483,
                giftOfTheNaaru  = 59543,
                roarOfSacrifice = 53480,
            },
            debuffs = {
                concussiveShot = 5116,
                misdirection   = 34477,
                scareBeast     = 1513,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                bindingShot       = 109248,
                camouflage        = 199483,
                concussiveShot    = 5116,
                misdirection      = 34477,
                roarOfSacrifice   = 53480,
                scareBeast        = 1513,
                tarTrap           = 187698,
                tranquilizingShot = 19801,
            },
        },
    },
    MAGE = {
        [62] = {
            abilities = {
                arcanePulse = 1241462,
                arcaneSurge = 365350,
            },
            buffs = {
                arcaneOrb        = 153626,
                evocation        = 12051,
                presenceOfMind   = 205025,
                prismaticBarrier = 235450,
                touchOfTheMagi   = 321507,
            },
            debuffs = {
                arcaneMissiles = 5143,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                arcaneMissiles   = 5143,
                arcaneOrb        = 153626,
                arcanePulse      = 1241462,
                arcaneSurge      = 365350,
                evocation        = 12051,
                presenceOfMind   = 205025,
                prismaticBarrier = 235450,
                touchOfTheMagi   = 321507,
            },
        },
        [63] = {
            abilities = {
                fireBlast           = 108853,
                flamestrike         = 2120,
                flamestrike_1254851 = 1254851,
                frostfireBolt       = 431044,
                meteor              = 153561,
                pyroblast           = 11366,
                scorch              = 2948,
            },
            buffs = {
                blazingBarrier = 235313,
                combustion     = 190319,
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                blazingBarrier      = 235313,
                combustion          = 190319,
                fireBlast           = 108853,
                flamestrike         = 2120,
                flamestrike_1254851 = 1254851,
                frostfireBolt       = 431044,
                meteor              = 153561,
                pyroblast           = 11366,
                scorch              = 2948,
            },
        },
        [64] = {
            abilities = {
                blizzard         = 190356,
                blizzard_1248829 = 1248829,
                coldSnap         = 235219,
                flurry           = 44614,
                frostfireBolt    = 431044,
                frozenOrb        = 84714,
                iceLance         = 30455,
            },
            buffs = {
                iceBarrier           = 11426,
                summonWaterElemental = 31687,
            },
            debuffs = {
                rayOfFrost = 205021,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                blizzard             = 190356,
                blizzard_1248829     = 1248829,
                coldSnap             = 235219,
                flurry               = 44614,
                frostfireBolt        = 431044,
                frozenOrb            = 84714,
                iceBarrier           = 11426,
                iceLance             = 30455,
                rayOfFrost           = 205021,
                summonWaterElemental = 31687,
            },
        },
        Shared = {
            abilities = {
                alterTime                  = 342245,
                ancientPortalDalaran       = 120146,
                ancientTeleportDalaran     = 120145,
                arcaneExplosion            = 1449,
                coneOfCold                 = 120,
                conjureRefreshment         = 190336,
                counterspell               = 2139,
                crittermorph               = 56599,
                dalaranBrilliance          = 292849,
                dragonsBreath              = 31661,
                ebonbolt                   = 214634,
                evaporation                = 147971,
                fireBlast                  = 319836,
                frostNova                  = 122,
                frostbolt                  = 116,
                greaterInvisibility        = 110959,
                iceNova                    = 157997,
                illusion                   = 131784,
                markOfAluneth              = 210726,
                markOfAluneth_211076       = 211076,
                markOfAluneth_211088       = 211088,
                phoenixsFlames             = 194466,
                portal                     = 343140,
                portalBoralus              = 281400,
                portalDalaranBrokenIsles   = 224871,
                portalDalaranNorthrend     = 53142,
                portalDarnassus            = 11419,
                portalDazaralor            = 281402,
                portalDornogal             = 446534,
                portalExodar               = 32266,
                portalIronforge            = 11416,
                portalOrgrimmar            = 11417,
                portalOribos               = 344597,
                portalShattrath            = 33691,
                portalShattrath_35717      = 35717,
                portalSilvermoon           = 32267,
                portalSilvermoonCity       = 1259194,
                portalStonard              = 49361,
                portalStormwind            = 10059,
                portalTheramore            = 49360,
                portalThunderBluff         = 11420,
                portalTolBarad             = 88345,
                portalTolBarad_88346       = 88346,
                portalUndercity            = 11418,
                portalValdrakken           = 395289,
                radiantSpark               = 307443,
                removeCurse                = 475,
                ringOfFrost                = 113724,
                shiftingPower              = 314791,
                spellsteal                 = 30449,
                supernova                  = 157980,
                teleport                   = 343127,
                teleportBoralus            = 281403,
                teleportDalaranBrokenIsles = 224869,
                teleportDalaranNorthrend   = 53140,
                teleportDarnassus          = 3565,
                teleportDazaralor          = 281404,
                teleportDornogal           = 446540,
                teleportExodar             = 32271,
                teleportIronforge          = 3562,
                teleportOrgrimmar          = 3567,
                teleportOribos             = 344587,
                teleportShattrath          = 33690,
                teleportShattrath_35715    = 35715,
                teleportSilvermoon         = 32272,
                teleportSilvermoonCity     = 1259190,
                teleportStonard            = 49358,
                teleportStormwind          = 3561,
                teleportTheramore          = 49359,
                teleportThunderBluff       = 3566,
                teleportTolBarad           = 88342,
                teleportTolBarad_88344     = 88344,
                teleportUndercity          = 3563,
                teleportValdrakken         = 395277,
                unboundElemental           = 147970,
            },
            buffs = {
                arcaneIntellect  = 1459,
                blink            = 1953,
                deathborne       = 324220,
                giftOfTheNaaru   = 59548,
                iceBlock         = 45438,
                invisibility     = 66,
                massInvisibility = 414664,
                massPolymorph    = 383121,
                mirrorImage      = 55342,
                shimmer          = 212653,
            },
            debuffs = {
                markOfAluneth    = 224968,
                mirrorsOfTorment = 314793,
                polymorph        = 118,
                polymorph_126819 = 126819,
                polymorph_161353 = 161353,
                polymorph_161354 = 161354,
                polymorph_161355 = 161355,
                polymorph_161372 = 161372,
                polymorph_277787 = 277787,
                polymorph_277792 = 277792,
                polymorph_28271  = 28271,
                polymorph_28272  = 28272,
                polymorph_321395 = 321395,
                polymorph_391622 = 391622,
                polymorph_460392 = 460392,
                polymorph_61025  = 61025,
                polymorph_61305  = 61305,
                polymorph_61721  = 61721,
                polymorph_61780  = 61780,
                slowFall         = 130,
                timeWarp         = 80353,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                alterTime           = 342245,
                dragonsBreath       = 31661,
                greaterInvisibility = 110959,
                iceBlock            = 45438,
                iceNova             = 157997,
                massInvisibility    = 414664,
                massPolymorph       = 383121,
                mirrorImage         = 55342,
                removeCurse         = 475,
                ringOfFrost         = 113724,
                shimmer             = 212653,
                spellsteal          = 30449,
                supernova           = 157980,
            },
        },
    },
    MONK = {
        [268] = {
            abilities = {
                breathOfFire            = 115181,
                chiBurst                = 123986,
                detox                   = 218164,
                explodingKeg            = 325153,
                invokeNiuzao,TheBlackOx = 132578,
                kegSmash                = 121253,
                purifyingBrew           = 119582,
                rushingJadeWind         = 116847,
                spearHandStrike         = 116705,
                summonBlackOxStatue     = 115315,
            },
            buffs = {
                blackOxBrew       = 115399,
                celestialBrew     = 322507,
                celestialInfusion = 1241059,
            },
            debuffs = {
                paralysis = 115078,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                blackOxBrew             = 115399,
                breathOfFire            = 115181,
                celestialBrew           = 322507,
                celestialInfusion       = 1241059,
                chiBurst                = 123986,
                detox                   = 218164,
                explodingKeg            = 325153,
                invokeNiuzao,TheBlackOx = 132578,
                kegSmash                = 121253,
                paralysis               = 115078,
                purifyingBrew           = 119582,
                rushingJadeWind         = 116847,
                spearHandStrike         = 116705,
                summonBlackOxStatue     = 115315,
            },
        },
        [269] = {
            abilities = {
                detox                    = 218164,
                fistsOfFury              = 113656,
                invokeXuen,TheWhiteTiger = 123904,
                risingSunKick            = 107428,
                spearHandStrike          = 116705,
                strikeOfTheWindlord      = 392983,
            },
            buffs = {
                slicingWinds        = 1217413,
                whirlingDragonPunch = 152175,
                zenith              = 1249625,
            },
            debuffs = {
                paralysis = 115078,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                detox                    = 218164,
                fistsOfFury              = 113656,
                invokeXuen,TheWhiteTiger = 123904,
                paralysis                = 115078,
                risingSunKick            = 107428,
                slicingWinds             = 1217413,
                spearHandStrike          = 116705,
                strikeOfTheWindlord      = 392983,
                whirlingDragonPunch      = 152175,
                zenith                   = 1249625,
            },
        },
        [270] = {
            abilities = {
                celestialConduit           = 443028,
                detox                      = 115450,
                envelopingMist             = 124682,
                invokeChiJi,TheRedCrane    = 325197,
                invokeYulon,TheJadeSerpent = 322118,
                reawaken                   = 212051,
                renewingMist               = 115151,
                restoral                   = 388615,
                revival                    = 115310,
                risingSunKick              = 107428,
                rushingWindKick            = 467307,
                sheilunsGift               = 399491,
                summonJadeSerpentStatue    = 115313,
            },
            buffs = {
                lifeCocoon      = 116849,
                thunderFocusTea = 116680,
            },
            debuffs = {
                paralysis = 115078,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                celestialConduit           = 443028,
                detox                      = 115450,
                envelopingMist             = 124682,
                invokeChiJi,TheRedCrane    = 325197,
                invokeYulon,TheJadeSerpent = 322118,
                lifeCocoon                 = 116849,
                paralysis                  = 115078,
                reawaken                   = 212051,
                renewingMist               = 115151,
                restoral                   = 388615,
                revival                    = 115310,
                risingSunKick              = 107428,
                rushingWindKick            = 467307,
                sheilunsGift               = 399491,
                summonJadeSerpentStatue    = 115313,
                thunderFocusTea            = 116680,
            },
        },
        Shared = {
            abilities = {
                blackoutKick            = 100784,
                chiTorpedo              = 115008,
                cracklingTigerLightning = 125932,
                expelHarm               = 322101,
                fallenOrder             = 326860,
                fightingPose            = 125874,
                honor                   = 125739,
                provoke                 = 115546,
                resuscitate             = 115178,
                ringOfPeace             = 116844,
                risingTigerKick         = 125152,
                roll                    = 109132,
                songOfChiJi             = 198898,
                tigerPalm               = 100780,
                touchOfDeath            = 322109,
                touchOfFatality         = 169340,
                transcendence           = 101643,
                vivify                  = 116670,
            },
            buffs = {
                arcaneTorrent       = 129597,
                bonedustBrew        = 325216,
                energyUsage         = 119650,
                faelineStomp        = 327104,
                giftOfTheNaaru      = 121093,
                renewingMist        = 119611,
                soothingMist        = 115175,
                soothingMist_209525 = 209525,
                tigersLust          = 116841,
                weaponsOfOrder      = 310454,
                zenFlight           = 125883,
            },
            debuffs = {
                disable = 116095,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                chiTorpedo    = 115008,
                disable       = 116095,
                ringOfPeace   = 116844,
                songOfChiJi   = 198898,
                soothingMist  = 115175,
                tigersLust    = 116841,
                transcendence = 101643,
            },
        },
    },
    PALADIN = {
        [65] = {
            abilities = {
                absolution           = 212056,
                auraMastery          = 31821,
                beaconOfFaith        = 156910,
                beaconOfLight        = 53563,
                cleanse              = 4987,
                cleanseToxins        = 440013,
                divineSteed          = 190784,
                eternalFlame         = 156322,
                holyBulwark          = 432459,
                holyLight            = 82326,
                judgment             = 275773,
                layOnHands           = 633,
                lightOfDawn          = 85222,
                riteOfAdjuration     = 433583,
                riteOfSanctification = 433568,
                shieldOfTheRighteous = 415091,
            },
            buffs = {
                avengingWrath    = 31884,
                beaconOfVirtue   = 200025,
                divineProtection = 498,
                divineToll       = 375576,
                holyPrism        = 114165,
                holyShock        = 20473,
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                absolution           = 212056,
                auraMastery          = 31821,
                avengingWrath        = 31884,
                beaconOfFaith        = 156910,
                beaconOfLight        = 53563,
                beaconOfVirtue       = 200025,
                cleanse              = 4987,
                cleanseToxins        = 440013,
                divineProtection     = 498,
                divineSteed          = 190784,
                divineToll           = 375576,
                eternalFlame         = 156322,
                holyBulwark          = 432459,
                holyLight            = 82326,
                holyPrism            = 114165,
                holyShock            = 20473,
                judgment             = 275773,
                layOnHands           = 633,
                lightOfDawn          = 85222,
                riteOfAdjuration     = 433583,
                riteOfSanctification = 433568,
                shieldOfTheRighteous = 415091,
            },
        },
        [66] = {
            abilities = {
                avengersShield       = 31935,
                cleanseToxins        = 213644,
                divineSteed          = 190784,
                hammerOfTheRighteous = 53595,
                holyBulwark          = 432459,
                layOnHands           = 633,
                rebuke               = 96231,
                riteOfAdjuration     = 433583,
                riteOfSanctification = 433568,
            },
            buffs = {
                ardentDefender         = 31850,
                avengingWrath          = 31884,
                blessedHammer          = 204019,
                divineToll             = 375576,
                guardianOfAncientKings = 86659,
                sentinel               = 389539,
            },
            debuffs = {
                blessingOfSpellwarding = 204018,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                ardentDefender         = 31850,
                avengersShield         = 31935,
                avengingWrath          = 31884,
                blessedHammer          = 204019,
                blessingOfSpellwarding = 204018,
                cleanseToxins          = 213644,
                divineSteed            = 190784,
                divineToll             = 375576,
                guardianOfAncientKings = 86659,
                hammerOfTheRighteous   = 53595,
                holyBulwark            = 432459,
                layOnHands             = 633,
                rebuke                 = 96231,
                riteOfAdjuration       = 433583,
                riteOfSanctification   = 433568,
                sentinel               = 389539,
            },
        },
        [70] = {
            abilities = {
                bladeOfJustice    = 184575,
                cleanseToxins     = 213644,
                divineStorm       = 53385,
                eternalFlame      = 156322,
                executionSentence = 343527,
                finalVerdict      = 383328,
                rebuke            = 96231,
                templarsVerdict   = 85256,
                wakeOfAshes       = 255937,
            },
            buffs = {
                avengingWrath    = 31884,
                divineProtection = 403876,
                divineToll       = 375576,
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                avengingWrath     = 31884,
                bladeOfJustice    = 184575,
                cleanseToxins     = 213644,
                divineProtection  = 403876,
                divineStorm       = 53385,
                divineToll        = 375576,
                eternalFlame      = 156322,
                executionSentence = 343527,
                finalVerdict      = 383328,
                rebuke            = 96231,
                templarsVerdict   = 85256,
                wakeOfAshes       = 255937,
            },
        },
        Shared = {
            abilities = {
                blessingOfSummer       = 328620,
                blindingLight          = 115750,
                crusaderStrike         = 35395,
                divineToll             = 304971,
                eyeOfTyr               = 209202,
                fireFromTheHeavens     = 58247,
                hammerOfWrath          = 24275,
                holyPrism              = 114871,
                holyShock              = 25912,
                intercession           = 391054,
                lightsHammer           = 114919,
                luminousCharger        = 55115,
                pillarOfLight          = 147974,
                redemption             = 7328,
                shieldOfTheRighteous   = 53600,
                tyrsDeliverance        = 200652,
                tyrsDeliverance_200654 = 200654,
                vanquishersHammer      = 328204,
                wakeOfAshes            = 205273,
                wingedVengeance        = 58244,
                wordOfGlory            = 85673,
            },
            buffs = {
                arcaneTorrent                = 155145,
                ashenHallow                  = 316958,
                blessingOfFreedom            = 1044,
                contemplation                = 121183,
                crusaderAura                 = 32223,
                crusadersDirehorn            = 290608,
                divineShield                 = 642,
                earthenOrdinantsRamolith     = 453785,
                giftOfTheNaaru               = 59542,
                holyLightstrider             = 356802,
                retributionAura              = 183435,
                senseUndead                  = 5502,
                summonCharger                = 23214,
                summonDarkforgeRam           = 270562,
                summonDawnforgeRam           = 270564,
                summonExarchsElekk           = 73629,
                summonGreatExarchsElekk      = 73630,
                summonGreatSunwalkerKodo     = 69826,
                summonLightforgedRuinstrider = 363613,
                summonSunwalkerKodo          = 69820,
                summonThalassianCharger      = 34767,
                summonThalassianWarhorse     = 34769,
                summonWarhorse               = 13819,
            },
            debuffs = {
                blessingOfProtection = 1022,
                blessingOfSacrifice  = 6940,
                handOfReckoning      = 62124,
                jailersJudgment      = 162056,
                turnEvil             = 10326,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                blessingOfFreedom    = 1044,
                blessingOfProtection = 1022,
                blessingOfSacrifice  = 6940,
                blindingLight        = 115750,
                turnEvil             = 10326,
            },
        },
    },
    PRIEST = {
        [256] = {
            abilities = {
                mindBlast         = 8092,
                powerWordBarrier  = 62618,
                powerWordRadiance = 194509,
                ultimatePenitence = 421453,
            },
            buffs = {
                evangelism      = 472433,
                painSuppression = 33206,
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                evangelism        = 472433,
                mindBlast         = 8092,
                painSuppression   = 33206,
                powerWordBarrier  = 62618,
                powerWordRadiance = 194509,
                ultimatePenitence = 421453,
            },
        },
        [257] = {
            abilities = {
                divineHymn       = 64843,
                holyFire         = 14914,
                holyNova         = 132157,
                holyWordChastise = 88625,
                holyWordSanctify = 34861,
                holyWordSerenity = 2050,
                prayerOfHealing  = 596,
            },
            buffs = {
                apotheosis     = 200183,
                guardianSpirit = 47788,
                halo           = 120517,
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                apotheosis       = 200183,
                divineHymn       = 64843,
                guardianSpirit   = 47788,
                halo             = 120517,
                holyFire         = 14914,
                holyNova         = 132157,
                holyWordChastise = 88625,
                holyWordSanctify = 34861,
                holyWordSerenity = 2050,
                prayerOfHealing  = 596,
            },
        },
        [258] = {
            abilities = {
                mindBlast     = 8092,
                purifyDisease = 213634,
                voidTorrent   = 263165,
                voidform      = 228260,
            },
            buffs = {
                halo         = 120644,
                tentacleSlam = 1227280,
            },
            debuffs = {
                psychicScream     = 8122,
                shadowWordMadness = 335467,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                halo              = 120644,
                mindBlast         = 8092,
                psychicScream     = 8122,
                purifyDisease     = 213634,
                shadowWordMadness = 335467,
                tentacleSlam      = 1227280,
                voidTorrent       = 263165,
                voidform          = 228260,
            },
        },
        Shared = {
            abilities = {
                angelicFeather  = 121536,
                dispelMagic     = 528,
                heavens         = 112660,
                inspiredHymns   = 148074,
                massDispel      = 32375,
                mindgames       = 323673,
                resurrection    = 2006,
                sha             = 148071,
                shackleUndead   = 58251,
                shadow          = 107905,
                shadowWordDeath = 32379,
                shadowyFriends  = 126797,
                smite           = 585,
                theValkyr       = 126695,
                unholyNova      = 324724,
            },
            buffs = {
                arcaneTorrent      = 232633,
                ascension          = 161862,
                boonOfTheAscended  = 325013,
                desperatePrayer    = 19236,
                fade               = 586,
                faeGuardians       = 327661,
                giftOfTheNaaru     = 59544,
                powerInfusion      = 10060,
                powerWordFortitude = 21562,
            },
            debuffs = {
                dominateMind  = 205364,
                leapOfFaith   = 73325,
                mindControl   = 605,
                shackleHorror = 9484,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                angelicFeather  = 121536,
                desperatePrayer = 19236,
                dispelMagic     = 528,
                dominateMind    = 205364,
                fade            = 586,
                leapOfFaith     = 73325,
                massDispel      = 32375,
                mindControl     = 605,
                powerInfusion   = 10060,
                shackleHorror   = 9484,
                shadowWordDeath = 32379,
            },
        },
    },
    ROGUE = {
        [259] = {
            abilities = {
                crimsonTempest = 1247227,
                kingsbane      = 385627,
                shiv           = 5938,
            },
            buffs = {
                amplifyingPoison = 381664,
                deadlyPoison     = 2823,
            },
            debuffs = {
                deathmark = 360194,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                amplifyingPoison = 381664,
                crimsonTempest   = 1247227,
                deadlyPoison     = 2823,
                deathmark        = 360194,
                kingsbane        = 385627,
                shiv             = 5938,
            },
        },
        [260] = {
            abilities = {
                bladeRush     = 271877,
                keepItRolling = 381989,
                preparation   = 1277933,
            },
            buffs = {
                adrenalineRush = 13750,
                killingSpree   = 51690,
            },
            debuffs = {
                blind = 2094,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                adrenalineRush = 13750,
                bladeRush      = 271877,
                blind          = 2094,
                keepItRolling  = 381989,
                killingSpree   = 51690,
                preparation    = 1277933,
            },
        },
        [261] = {
            abilities = {
                cloakOfShadows = 31224,
                gloomblade     = 200758,
                goremawsBite   = 426591,
            },
            buffs = {
                shadowBlades = 121471,
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                cloakOfShadows = 31224,
                gloomblade     = 200758,
                goremawsBite   = 426591,
                shadowBlades   = 121471,
            },
        },
        Shared = {
            abilities = {
                ambush            = 8676,
                disguise          = 63899,
                distract          = 1725,
                echoingReprimand  = 323547,
                flagellation      = 323654,
                kick              = 1766,
                pickLock          = 1804,
                serratedBoneSpike = 328547,
            },
            buffs = {
                arcaneTorrent    = 25046,
                atrophicPoison   = 381637,
                crimsonVial      = 185311,
                cripplingPoison  = 3408,
                detection        = 56814,
                evasion          = 5277,
                feint            = 1966,
                giftOfTheNaaru   = 370626,
                instantPoison    = 315584,
                numbingPoison    = 5761,
                sliceAndDice     = 315496,
                sprint           = 2983,
                tricksOfTheTrade = 57934,
            },
            debuffs = {
                gouge      = 1776,
                kidneyShot = 408,
                sap        = 6770,
                sepsis     = 328305,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                atrophicPoison   = 381637,
                evasion          = 5277,
                gouge            = 1776,
                numbingPoison    = 5761,
                tricksOfTheTrade = 57934,
            },
        },
    },
    SHAMAN = {
        [262] = {
            abilities = {
                ascendance        = 114050,
                cleanseSpirit     = 51886,
                earthShock        = 8042,
                elementalBlast    = 117014,
                flametongueWeapon = 318038,
                thunderstorm      = 51490,
            },
            buffs = {
                earthquake        = 61882,
                earthquake_462620 = 462620,
                lavaBurst         = 51505,
                stormkeeper       = 191634,
                thunderstrikeWard = 462757,
                voltaicBlaze      = 470057,
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                ascendance        = 114050,
                cleanseSpirit     = 51886,
                earthShock        = 8042,
                earthquake        = 61882,
                earthquake_462620 = 462620,
                elementalBlast    = 117014,
                flametongueWeapon = 318038,
                lavaBurst         = 51505,
                stormkeeper       = 191634,
                thunderstorm      = 51490,
                thunderstrikeWard = 462757,
                voltaicBlaze      = 470057,
            },
        },
        [263] = {
            abilities = {
                ascendance        = 114051,
                cleanseSpirit     = 51886,
                crashLightning    = 187874,
                doomWinds         = 384352,
                feralLunge        = 196884,
                flametongueWeapon = 318038,
                lavaLash          = 60103,
                stormstrike       = 17364,
                sundering         = 197214,
                windfuryWeapon    = 33757,
            },
            buffs = {
                voltaicBlaze = 470057,
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                ascendance        = 114051,
                cleanseSpirit     = 51886,
                crashLightning    = 187874,
                doomWinds         = 384352,
                feralLunge        = 196884,
                flametongueWeapon = 318038,
                lavaLash          = 60103,
                stormstrike       = 17364,
                sundering         = 197214,
                voltaicBlaze      = 470057,
                windfuryWeapon    = 33757,
            },
        },
        [264] = {
            abilities = {
                ancestralVision  = 212048,
                ascendance       = 114052,
                chainHeal        = 1064,
                cleanseSpirit    = 440012,
                healingTideTotem = 108280,
                healingWave      = 77472,
                purifySpirit     = 77130,
                riptide          = 61295,
                spiritLinkTotem  = 98008,
                unleashLife      = 73685,
            },
            buffs = {
                earthlivingWeapon = 382021,
                healingRain       = 73920,
                lavaBurst         = 51505,
                waterShield       = 52127,
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                ancestralVision   = 212048,
                ascendance        = 114052,
                chainHeal         = 1064,
                cleanseSpirit     = 440012,
                earthlivingWeapon = 382021,
                healingRain       = 73920,
                healingTideTotem  = 108280,
                healingWave       = 77472,
                lavaBurst         = 51505,
                purifySpirit      = 77130,
                riptide           = 61295,
                spiritLinkTotem   = 98008,
                unleashLife       = 73685,
                waterShield       = 52127,
            },
        },
        Shared = {
            abilities = {
                ancestralSpirit      = 2008,
                astralRecall         = 556,
                capacitorTotem       = 192058,
                chainHarvest         = 320674,
                chainLightning       = 188443,
                earthbindTotem       = 2484,
                earthgrabTotem       = 51485,
                faeTransfusion       = 328923,
                frostShock           = 196840,
                greaterPurge         = 378773,
                gustOfWind           = 192063,
                healingSurge         = 8004,
                lightningBolt        = 188196,
                lingeringAncestors   = 148080,
                poisonCleansingTotem = 383013,
                primalStrike         = 73899,
                primordialWave       = 326059,
                purge                = 370,
                spectralWolf         = 58261,
                spiritRaptors        = 148079,
                spiritWalk           = 58875,
                totemicProjection    = 108287,
                tremorTotem          = 8143,
                vesperTotem          = 324386,
                windRushTotem        = 192077,
                windShear            = 57994,
            },
            buffs = {
                astralShift        = 108271,
                earthElemental     = 198103,
                earthShield        = 974,
                farSight           = 6196,
                ghostWolf          = 2645,
                giftOfTheNaaru     = 59547,
                lightningShield    = 192106,
                naturesSwiftness   = 378081,
                spiritwalkersGrace = 79206,
                waterWalking       = 546,
            },
            debuffs = {
                bloodlust  = 2825,
                heroism    = 32182,
                hex        = 51514,
                hex_210873 = 210873,
                hex_211004 = 211004,
                hex_211010 = 211010,
                hex_211015 = 211015,
                hex_269352 = 269352,
                hex_277778 = 277778,
                hex_277784 = 277784,
                hex_309328 = 309328,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                astralShift          = 108271,
                capacitorTotem       = 192058,
                chainLightning       = 188443,
                earthElemental       = 198103,
                earthShield          = 974,
                earthgrabTotem       = 51485,
                frostShock           = 196840,
                greaterPurge         = 378773,
                gustOfWind           = 192063,
                hex                  = 51514,
                naturesSwiftness     = 378081,
                poisonCleansingTotem = 383013,
                purge                = 370,
                spiritWalk           = 58875,
                spiritwalkersGrace   = 79206,
                totemicProjection    = 108287,
                tremorTotem          = 8143,
                windRushTotem        = 192077,
                windShear            = 57994,
            },
        },
    },
    WARLOCK = {
        [265] = {
            abilities = {
                darkHarvest         = 1257052,
                grimoireOfSacrifice = 108503,
                haunt               = 48181,
                summonDarkglare     = 205180,
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                agony              = 980,
                seedOfCorruption   = 27243,
                unstableAffliction = 1259790,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                agony               = 980,
                darkHarvest         = 1257052,
                grimoireOfSacrifice = 108503,
                haunt               = 48181,
                seedOfCorruption    = 27243,
                summonDarkglare     = 205180,
                unstableAffliction  = 1259790,
            },
        },
        [266] = {
            abilities = {
                callDreadstalkers   = 104316,
                grimoireFelRavager  = 1276467,
                grimoireImpLord     = 1276452,
                implosion           = 196277,
                powerSiphon         = 264130,
                summonDemonicTyrant = 265187,
                summonDoomguard     = 1276672,
                summonFelguard      = 30146,
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                callDreadstalkers   = 104316,
                grimoireFelRavager  = 1276467,
                grimoireImpLord     = 1276452,
                implosion           = 196277,
                powerSiphon         = 264130,
                summonDemonicTyrant = 265187,
                summonDoomguard     = 1276672,
                summonFelguard      = 30146,
            },
        },
        [267] = {
            abilities = {
                cataclysm           = 152108,
                chaosBolt           = 116858,
                conflagrate         = 17962,
                grimoireOfSacrifice = 108503,
                shadowburn          = 17877,
                soulFire            = 6353,
                summonInfernal      = 1122,
            },
            buffs = {
                channelDemonfire   = 196447,
                rainOfFire         = 5740,
                rainOfFire_1214467 = 1214467,
            },
            debuffs = {
                havoc = 80240,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                cataclysm           = 152108,
                channelDemonfire    = 196447,
                chaosBolt           = 116858,
                conflagrate         = 17962,
                grimoireOfSacrifice = 108503,
                havoc               = 80240,
                rainOfFire          = 5740,
                rainOfFire_1214467  = 1214467,
                shadowburn          = 17877,
                soulFire            = 6353,
                summonInfernal      = 1122,
            },
        },
        Shared = {
            abilities = {
                blightOfTongues          = 1271802,
                commandDemon             = 119898,
                createHealthstone        = 6201,
                createSoulwell           = 29893,
                crimsonBanish            = 63943,
                decimatingBolt           = 325289,
                demonicGateway           = 111771,
                eyeOfKilrogg             = 126,
                fear                     = 5782,
                felguard                 = 56285,
                impendingCatastrophe     = 321792,
                lordBanehollowsSoulstone = 416229,
                ritualOfDoom             = 342601,
                scouringTithe            = 312321,
                shadowBolt               = 686,
                soulburn                 = 385899,
                soulstone                = 20707,
                soulwell                 = 58275,
                summonFelhunter          = 691,
                summonImp                = 688,
                summonSayaad             = 366222,
                summonVoidwalker         = 697,
            },
            buffs = {
                burningRush       = 111400,
                controlDemon      = 93375,
                darkPact          = 108416,
                dreadsteed        = 23161,
                felDomination     = 333889,
                felsteed          = 5784,
                giftOfTheNaaru    = 416250,
                ritualOfSummoning = 698,
                shadowfury        = 30283,
                unendingBreath    = 5697,
                unendingResolve   = 104773,
            },
            debuffs = {
                banish            = 710,
                corruption        = 146739,
                curseOfExhaustion = 334275,
                curseOfTongues    = 1714,
                curseOfWeakness   = 702,
                howlOfTerror      = 5484,
                mortalCoil        = 6789,
                soulRot           = 325640,
                subjugateDemon    = 1098,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                banish            = 710,
                blightOfTongues   = 1271802,
                burningRush       = 111400,
                curseOfExhaustion = 334275,
                curseOfTongues    = 1714,
                darkPact          = 108416,
                demonicGateway    = 111771,
                felDomination     = 333889,
                howlOfTerror      = 5484,
                mortalCoil        = 6789,
                shadowfury        = 30283,
                soulburn          = 385899,
            },
        },
    },
    WARRIOR = {
        [65] = {
            abilities = {
                singleButtonAssistant = 1229376,
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                singleButtonAssistant = 1229376,
            },
        },
        [70] = {
            abilities = {
                singleButtonAssistant = 1229376,
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                singleButtonAssistant = 1229376,
            },
        },
        [71] = {
            abilities = {
                bladestorm            = 227847,
                cleave                = 845,
                colossusSmash         = 167105,
                interpose             = 1244088,
                intervene             = 3411,
                mortalStrike          = 12294,
                overpower             = 7384,
                singleButtonAssistant = 1229376,
            },
            buffs = {
                avatar          = 107574,
                battleStance    = 386164,
                defensiveStance = 386208,
                dieByTheSword   = 118038,
                ignorePain      = 1277297,
                ravager         = 228920,
                sweepingStrikes = 260708,
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                avatar                = 107574,
                battleStance          = 386164,
                bladestorm            = 227847,
                cleave                = 845,
                colossusSmash         = 167105,
                defensiveStance       = 386208,
                dieByTheSword         = 118038,
                ignorePain            = 1277297,
                interpose             = 1244088,
                intervene             = 3411,
                mortalStrike          = 12294,
                overpower             = 7384,
                ravager               = 228920,
                singleButtonAssistant = 1229376,
                sweepingStrikes       = 260708,
            },
        },
        [72] = {
            abilities = {
                bladestorm            = 227847,
                bloodthirst           = 23881,
                execute               = 5308,
                interpose             = 1244088,
                intervene             = 3411,
                odynsFury             = 385059,
                ragingBlow            = 85288,
                rampage               = 184367,
                singleButtonAssistant = 1229376,
                whirlwind             = 190411,
            },
            buffs = {
                avatar              = 107574,
                berserkerStance     = 386196,
                defensiveStance     = 386208,
                enragedRegeneration = 184364,
                recklessness        = 1719,
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                avatar                = 107574,
                berserkerStance       = 386196,
                bladestorm            = 227847,
                bloodthirst           = 23881,
                defensiveStance       = 386208,
                enragedRegeneration   = 184364,
                execute               = 5308,
                interpose             = 1244088,
                intervene             = 3411,
                odynsFury             = 385059,
                ragingBlow            = 85288,
                rampage               = 184367,
                recklessness          = 1719,
                singleButtonAssistant = 1229376,
                whirlwind             = 190411,
            },
        },
        [73] = {
            abilities = {
                intervene    = 3411,
                revenge      = 6572,
                shieldCharge = 385952,
            },
            buffs = {
                avatar            = 107574,
                battleStance      = 386164,
                defensiveStance   = 386208,
                demoralizingShout = 1160,
                disruptingShout   = 386071,
                ignorePain        = 190456,
                ravager           = 228920,
                shieldWall        = 871,
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                avatar            = 107574,
                battleStance      = 386164,
                defensiveStance   = 386208,
                demoralizingShout = 1160,
                disruptingShout   = 386071,
                ignorePain        = 190456,
                intervene         = 3411,
                ravager           = 228920,
                revenge           = 6572,
                shieldCharge      = 385952,
                shieldWall        = 871,
            },
        },
        [102] = {
            abilities = {
                singleButtonAssistant = 1229376,
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                singleButtonAssistant = 1229376,
            },
        },
        [105] = {
            abilities = {
                singleButtonAssistant = 1229376,
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                singleButtonAssistant = 1229376,
            },
        },
        [250] = {
            abilities = {
                singleButtonAssistant = 1229376,
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                singleButtonAssistant = 1229376,
            },
        },
        [251] = {
            abilities = {
                singleButtonAssistant = 1229376,
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                singleButtonAssistant = 1229376,
            },
        },
        [252] = {
            abilities = {
                singleButtonAssistant = 1229376,
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                singleButtonAssistant = 1229376,
            },
        },
        [253] = {
            abilities = {
                singleButtonAssistant = 1229376,
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                singleButtonAssistant = 1229376,
            },
        },
        [254] = {
            abilities = {
                singleButtonAssistant = 1229376,
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                singleButtonAssistant = 1229376,
            },
        },
        [262] = {
            abilities = {
                singleButtonAssistant = 1229376,
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                singleButtonAssistant = 1229376,
            },
        },
        [263] = {
            abilities = {
                singleButtonAssistant = 1229376,
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                singleButtonAssistant = 1229376,
            },
        },
        [264] = {
            abilities = {
                singleButtonAssistant = 1229376,
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                singleButtonAssistant = 1229376,
            },
        },
        [270] = {
            abilities = {
                singleButtonAssistant = 1229376,
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                singleButtonAssistant = 1229376,
            },
        },
        [1480] = {
            abilities = {
                singleButtonAssistant = 1229376,
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                singleButtonAssistant = 1229376,
            },
        },
        Shared = {
            abilities = {
                ancientAftershock = 325886,
                attack            = 88163,
                berserkerShout    = 384100,
                blazingTrail      = 123780,
                burningAnger      = 112793,
                championsSpear    = 376079,
                conquerorsBanner  = 324143,
                execute           = 163201,
                gushingWound      = 58279,
                hamstring         = 1715,
                hawkFeast         = 112792,
                heroicLeap        = 6544,
                heroicLeap_52174  = 52174,
                heroicThrow       = 57755,
                impendingVictory  = 202168,
                mightyVictory     = 58281,
                piercingHowl      = 12323,
                pummel            = 6552,
                ragingBlow        = 85384,
                ragingBlow_96103  = 96103,
                rallyingCry       = 97462,
                rend              = 772,
                shatteringThrow   = 64382,
                shieldBlock       = 2565,
                shieldSlam        = 23922,
                shockwave         = 46968,
                slam              = 1464,
                spearOfBastion    = 307865,
                spellReflection   = 23920,
                stormBolt         = 107570,
                thunderClap       = 6343,
                thunderStrike     = 68163,
                weaponmaster      = 148114,
                whirlwindOffHand  = 44949,
                wreckingThrow     = 384110,
            },
            buffs = {
                arcaneTorrent  = 69179,
                berserkerRage  = 18499,
                charge         = 100,
                giftOfTheNaaru = 28880,
            },
            debuffs = {
                battleShout       = 6673,
                intimidatingShout = 5246,
                taunt             = 355,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                berserkerShout    = 384100,
                championsSpear    = 376079,
                heroicLeap        = 6544,
                impendingVictory  = 202168,
                intimidatingShout = 5246,
                piercingHowl      = 12323,
                rallyingCry       = 97462,
                rend              = 772,
                shatteringThrow   = 64382,
                shockwave         = 46968,
                spellReflection   = 23920,
                stormBolt         = 107570,
                thunderClap       = 6343,
                wreckingThrow     = 384110,
            },
        },
    },
}
