local _, br = ...
if br.lists == nil then br.lists = {} end

-- Generated by BreweryNav spell generator
-- Source build : 12.0.1.66384
-- Extracted at : 2026-03-26T01:06:35Z
-- DO NOT EDIT  — regenerate from BreweryNav.Extractor.SpellIds

br.lists.spells = {
    DEATHKNIGHT = {
        [250] = {
            abilities = {
                -- (none)
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                deathsCaress = 195292,
            },
        },
        [251] = {
            abilities = {
                -- (none)
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                glacialAdvance    = 194913,
                remorselessWinter = 196770,
            },
        },
        [252] = {
            abilities = {
                -- (none)
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                epidemic        = 207317,
                festeringStrike = 85948,
                raiseDead       = 46584,
            },
        },
        Shared = {
            abilities = {
                abominationLimb            = 315443,
                chainsOfIce                = 45524,
                consumption                = 205223,
                consumption_205224         = 205224,
                deathCoil                  = 47541,
                deathGate                  = 50977,
                deathGrip                  = 49576,
                foulMenagerie              = 58723,
                frostBreath                = 190780,
                geist                      = 58707,
                packHobgoblin              = 69046,
                raiseAlly                  = 61999,
                runeOfRazorice             = 53343,
                runeOfSanguination         = 326805,
                runeOfSpellwarding         = 326855,
                runeOfTheApocalypse        = 327082,
                runeOfTheFallenCrusader    = 53344,
                runeOfTheStoneskinGargoyle = 62158,
                runeOfUnendingThirst       = 326977,
                runeStrike                 = 316239,
                runeforging                = 53428,
                sindragosasFury            = 190778,
                skeleton                   = 147963,
                swarmingMist               = 311648,
                twoForms                   = 68996,
            },
            buffs = {
                acherusDeathcharger       = 48778,
                antiMagicShell            = 48707,
                apocalypse                = 220143,
                arcaneTorrent             = 50613,
                calmTheWolf               = 406087,
                darkflight                = 68992,
                deathAndDecay             = 43265,
                deathsAdvance             = 48265,
                giftOfTheNaaru            = 59545,
                lichborne                 = 49039,
                pathOfFrost               = 3714,
                wingedSteedOfTheEbonBlade = 54729,
            },
            debuffs = {
                bloodPlague        = 55078,
                corpseExploder     = 127344,
                darkCommand        = 56222,
                frostFever         = 55095,
                shackleTheUnworthy = 312202,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                abominationLimb    = 1263569,
                antiMagicZone      = 51052,
                armyOfTheDead      = 42650,
                asphyxiate         = 221562,
                blindingSleet      = 207167,
                bloodBoil          = 50842,
                breathOfSindragosa = 1249658,
                consumption        = 1263824,
                controlUndead      = 111673,
                dancingRuneWeapon  = 49028,
                darkTransformation = 1233448,
                deathPact          = 48743,
                deathStrike        = 49998,
                empowerRuneWeapon  = 47568,
                frostStrike        = 49143,
                frostscythe        = 207230,
                frostwyrmsFury     = 279302,
                gorefiendsGrasp    = 108199,
                heartStrike        = 206930,
                howlingBlast       = 49184,
                iceboundFortitude  = 48792,
                marrowrend         = 195182,
                mindFreeze         = 47528,
                obliterate         = 49020,
                outbreak           = 77575,
                pillarOfFrost      = 51271,
                putrefy            = 1247378,
                raiseDead          = 46585,
                reapersMark        = 439843,
                scourgeStrike      = 55090,
                soulReaper         = 343294,
                vampiricBlood      = 55233,
                wraithWalk         = 212552,
            },
        },
    },
    DEMONHUNTER = {
        [1480] = {
            abilities = {
                -- (none)
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                blur              = 198589,
                consume           = 473662,
                reap              = 1226019,
                shift             = 1234796,
                spectralSight     = 1251417,
                voidMetamorphosis = 1217605,
            },
        },
        Shared = {
            abilities = {
                activatingSpecialization = 200749,
                demonsBite               = 344859,
                disrupt                  = 183752,
                elysianDecree            = 306830,
                immolationAura           = 258920,
                sigilOfFlame             = 204596,
            },
            buffs = {
                arcaneTorrent = 202719,
                felsaber      = 200175,
                groveDefiler  = 193007,
            },
            debuffs = {
                sinfulBrand = 317009,
                torment     = 185245,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                chaosNova       = 179057,
                consumeMagic    = 278326,
                darkness        = 196718,
                essenceBreak    = 258860,
                eyeBeam         = 198013,
                felDevastation  = 212084,
                felblade        = 232893,
                fieryBrand      = 204021,
                imprison        = 217832,
                sigilOfChains   = 202138,
                sigilOfMisery   = 207684,
                sigilOfSilence  = 202137,
                sigilOfSpite    = 390163,
                soulCarver      = 207407,
                soulImmolation  = 1241937,
                spiritBomb      = 247454,
                vengefulRetreat = 198793,
                voidNova        = 1234195,
                voidRay         = 473728,
                voidblade       = 1245412,
            },
        },
    },
    DRUID = {
        [102] = {
            abilities = {
                -- (none)
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                shapeshiftForm = 228545,
                starfall       = 191034,
                wrath          = 190984,
            },
        },
        [105] = {
            abilities = {
                -- (none)
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                naturesCure      = 88423,
                removeCorruption = 440015,
                revitalize       = 212040,
            },
        },
        Shared = {
            abilities = {
                adaptiveSwarm     = 325727,
                ferociousBite     = 22568,
                mangle            = 33917,
                markOfTheCheetah  = 131151,
                markOfTheOrca     = 54872,
                revive            = 50769,
                shred             = 5221,
                theSun            = 171891,
                theUrsolChameleon = 58158,
                yserasGift        = 145109,
                yserasGift_145110 = 145110,
            },
            buffs = {
                convokeTheSpirits = 323764,
                flightForm        = 165962,
                kindredSpirits    = 326434,
                markOfTheWild     = 1126,
                ravenousFrenzy    = 323546,
            },
            debuffs = {
                growl = 6795,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                berserk                     = 50334,
                bristlingFur                = 155835,
                chomp                       = 1244258,
                convokeTheSpirits           = 391528,
                cyclone                     = 33786,
                efflorescence               = 145205,
                feralFrenzy                 = 274837,
                forceOfNature               = 205636,
                franticFrenzy               = 1243807,
                frenziedRegeneration        = 22842,
                furyOfElune                 = 202770,
                heartOfTheWild              = 1261867,
                hibernate                   = 2637,
                incapacitatingRoar          = 99,
                incarnationAvatarOfAshamane = 102543,
                incarnationGuardianOfUrsoc  = 102558,
                incarnationTreeOfLife       = 33891,
                innervate                   = 29166,
                ironbark                    = 102342,
                ironfur                     = 192081,
                lifebloom                   = 33763,
                lunarBeam                   = 204066,
                maim                        = 22570,
                massEntanglement            = 102359,
                maul                        = 6807,
                mightyBash                  = 5211,
                moonkinForm                 = 24858,
                moonkinForm_197625          = 197625,
                naturesSwiftness            = 132158,
                newMoon                     = 274281,
                primalWrath                 = 285381,
                rake                        = 1822,
                raze                        = 400254,
                redMoon                     = 1252871,
                rejuvenation                = 774,
                removeCorruption            = 2782,
                rip                         = 1079,
                skullBash                   = 106839,
                solarBeam                   = 78675,
                soothe                      = 2908,
                stampedingRoar              = 106898,
                starfire                    = 194153,
                starfire_197628             = 197628,
                starsurge                   = 78674,
                starsurge_197626            = 197626,
                sunderingRoar               = 1253799,
                sunfire                     = 93402,
                survivalInstincts           = 61336,
                swiftmend                   = 18562,
                swipe                       = 213764,
                symbioticRelationship       = 474750,
                tigerDash                   = 252216,
                tigersFury                  = 5217,
                tranquility                 = 740,
                typhoon                     = 132469,
                ursolsVortex                = 102793,
                wildCharge                  = 102401,
                wildGrowth                  = 48438,
                wildMushroom                = 88747,
            },
        },
    },
    EVOKER = {
        Shared = {
            abilities = {
                azureStrike         = 362969,
                blessingOfTheBronze = 364342,
                boonOfTheCovenants  = 387168,
                emeraldBlossom      = 355913,
                livingFlame         = 361469,
                return              = 361227,
                skywardAscent       = 376744,
                visage              = 351239,
            },
            buffs = {
                aerialHalt     = 403216,
                chosenIdentity = 360022,
                deepBreath     = 357210,
                fireBreath     = 357208,
                hover          = 358267,
                soar           = 369536,
                surgeForward   = 376743,
                tailSwipe      = 368970,
            },
            debuffs = {
                disintegrate     = 356995,
                furyOfTheAspects = 390386,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                bestowWeyrnstone = 408233,
                blisteringScales = 360827,
                breathOfEons     = 403631,
                cauterizingFlame = 374251,
                dragonrage       = 375087,
                dreamBreath      = 355936,
                dreamFlight      = 359816,
                ebonMight        = 395152,
                echo             = 364343,
                eruption         = 395160,
                eternitySurge    = 359073,
                expunge          = 365585,
                landslide        = 358385,
                obsidianScales   = 363916,
                oppressingRoar   = 372048,
                prescience       = 409311,
                pyre             = 357211,
                quell            = 351338,
                rescue           = 370665,
                reversion        = 366155,
                rewind           = 363534,
                sleepWalk        = 360806,
                sourceOfMagic    = 369459,
                spatialParadox   = 406732,
                stasis           = 370537,
                temporalAnomaly  = 373861,
                timeDilation     = 357170,
                timeSkip         = 404977,
                timeSpiral       = 374968,
                timelessness     = 412710,
                tipTheScales     = 370553,
                upheaval         = 396286,
                verdantEmbrace   = 360995,
                zephyr           = 374227,
            },
        },
    },
    HUNTER = {
        [253] = {
            abilities = {
                -- (none)
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                eyesOfTheBeast = 321297,
            },
        },
        [254] = {
            abilities = {
                -- (none)
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                eagleEye    = 6197,
                harriersCry = 466904,
                multiShot   = 257620,
            },
        },
        Shared = {
            abilities = {
                autoShot         = 75,
                commandPet       = 272651,
                deathChakram     = 325028,
                flayedShot       = 324149,
                lesserProportion = 58188,
                resonatingArrow  = 308491,
                wildSpirits      = 328231,
            },
            buffs = {
                arcaneTorrent  = 80483,
                giftOfTheNaaru = 59543,
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                aimedShot            = 19434,
                barbedShot           = 217200,
                bestialWrath         = 19574,
                bindingShot          = 109248,
                blackArrow           = 466930,
                boomstick            = 1261193,
                camouflage           = 199483,
                cobraShot            = 193455,
                concussiveShot       = 5116,
                counterShot          = 147362,
                flamefangPitch       = 1251592,
                intimidation         = 19577,
                intimidation_474421  = 474421,
                killCommand          = 34026,
                killCommand_259489   = 259489,
                killShot             = 53351,
                misdirection         = 34477,
                muzzle               = 187707,
                rapidFire            = 257044,
                raptorStrike         = 186270,
                roarOfSacrifice      = 53480,
                scareBeast           = 1513,
                survivalOfTheFittest = 264735,
                takedown             = 1250646,
                tarTrap              = 187698,
                tranquilizingShot    = 19801,
                trueshot             = 288613,
                volley               = 260243,
                wildThrash           = 1264359,
                wildfireBomb         = 259495,
            },
        },
    },
    MAGE = {
        Shared = {
            abilities = {
                ancientPortalDalaran       = 120146,
                ancientTeleportDalaran     = 120145,
                arcaneExplosion            = 1449,
                coneOfCold                 = 120,
                conjureRefreshment         = 190336,
                counterspell               = 2139,
                crittermorph               = 56599,
                dalaranBrilliance          = 292849,
                ebonbolt                   = 214634,
                evaporation                = 147971,
                fireBlast                  = 319836,
                frostNova                  = 122,
                frostbolt                  = 116,
                illusion                   = 131784,
                markOfAluneth              = 210726,
                markOfAluneth_211076       = 211076,
                markOfAluneth_211088       = 211088,
                phoenixsFlames             = 194466,
                portal                     = 343140,
                portalBoralus              = 281400,
                portalDalaranBrokenIsles   = 224871,
                portalDalaranNorthrend     = 53142,
                portalDarnassus            = 11419,
                portalDazaralor            = 281402,
                portalDornogal             = 446534,
                portalExodar               = 32266,
                portalIronforge            = 11416,
                portalOrgrimmar            = 11417,
                portalOribos               = 344597,
                portalShattrath            = 33691,
                portalShattrath_35717      = 35717,
                portalSilvermoon           = 32267,
                portalSilvermoonCity       = 1259194,
                portalStonard              = 49361,
                portalStormwind            = 10059,
                portalTheramore            = 49360,
                portalThunderBluff         = 11420,
                portalTolBarad             = 88345,
                portalTolBarad_88346       = 88346,
                portalUndercity            = 11418,
                portalValdrakken           = 395289,
                radiantSpark               = 307443,
                shiftingPower              = 314791,
                teleport                   = 343127,
                teleportBoralus            = 281403,
                teleportDalaranBrokenIsles = 224869,
                teleportDalaranNorthrend   = 53140,
                teleportDarnassus          = 3565,
                teleportDazaralor          = 281404,
                teleportDornogal           = 446540,
                teleportExodar             = 32271,
                teleportIronforge          = 3562,
                teleportOrgrimmar          = 3567,
                teleportOribos             = 344587,
                teleportShattrath          = 33690,
                teleportShattrath_35715    = 35715,
                teleportSilvermoon         = 32272,
                teleportSilvermoonCity     = 1259190,
                teleportStonard            = 49358,
                teleportStormwind          = 3561,
                teleportTheramore          = 49359,
                teleportThunderBluff       = 3566,
                teleportTolBarad           = 88342,
                teleportTolBarad_88344     = 88344,
                teleportUndercity          = 3563,
                teleportValdrakken         = 395277,
                unboundElemental           = 147970,
            },
            buffs = {
                arcaneIntellect = 1459,
                blink           = 1953,
                deathborne      = 324220,
                giftOfTheNaaru  = 59548,
                invisibility    = 66,
            },
            debuffs = {
                markOfAluneth    = 224968,
                mirrorsOfTorment = 314793,
                polymorph        = 118,
                polymorph_126819 = 126819,
                polymorph_161353 = 161353,
                polymorph_161354 = 161354,
                polymorph_161355 = 161355,
                polymorph_161372 = 161372,
                polymorph_277787 = 277787,
                polymorph_277792 = 277792,
                polymorph_28271  = 28271,
                polymorph_28272  = 28272,
                polymorph_321395 = 321395,
                polymorph_391622 = 391622,
                polymorph_460392 = 460392,
                polymorph_61025  = 61025,
                polymorph_61305  = 61305,
                polymorph_61721  = 61721,
                polymorph_61780  = 61780,
                slowFall         = 130,
                timeWarp         = 80353,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                alterTime            = 342245,
                arcaneMissiles       = 5143,
                arcaneOrb            = 153626,
                arcanePulse          = 1241462,
                arcaneSurge          = 365350,
                blazingBarrier       = 235313,
                blizzard             = 190356,
                blizzard_1248829     = 1248829,
                coldSnap             = 235219,
                combustion           = 190319,
                dragonsBreath        = 31661,
                evocation            = 12051,
                fireBlast            = 108853,
                flamestrike          = 2120,
                flamestrike_1254851  = 1254851,
                flurry               = 44614,
                frostfireBolt        = 431044,
                frozenOrb            = 84714,
                greaterInvisibility  = 110959,
                iceBarrier           = 11426,
                iceBlock             = 45438,
                iceLance             = 30455,
                iceNova              = 157997,
                massInvisibility     = 414664,
                massPolymorph        = 383121,
                meteor               = 153561,
                mirrorImage          = 55342,
                presenceOfMind       = 205025,
                prismaticBarrier     = 235450,
                pyroblast            = 11366,
                rayOfFrost           = 205021,
                removeCurse          = 475,
                ringOfFrost          = 113724,
                scorch               = 2948,
                shimmer              = 212653,
                spellsteal           = 30449,
                summonWaterElemental = 31687,
                supernova            = 157980,
                touchOfTheMagi       = 321507,
            },
        },
    },
    MONK = {
        [270] = {
            abilities = {
                -- (none)
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                detox        = 115450,
                reawaken     = 212051,
                renewingMist = 115151,
            },
        },
        Shared = {
            abilities = {
                blackoutKick            = 100784,
                cracklingTigerLightning = 125932,
                expelHarm               = 322101,
                fallenOrder             = 326860,
                fightingPose            = 125874,
                honor                   = 125739,
                provoke                 = 115546,
                resuscitate             = 115178,
                risingTigerKick         = 125152,
                roll                    = 109132,
                tigerPalm               = 100780,
                touchOfDeath            = 322109,
                touchOfFatality         = 169340,
                vivify                  = 116670,
            },
            buffs = {
                arcaneTorrent  = 129597,
                bonedustBrew   = 325216,
                energyUsage    = 119650,
                faelineStomp   = 327104,
                giftOfTheNaaru = 121093,
                renewingMist   = 119611,
                soothingMist   = 209525,
                weaponsOfOrder = 310454,
                zenFlight      = 125883,
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                blackOxBrew                = 115399,
                breathOfFire               = 115181,
                celestialBrew              = 322507,
                celestialConduit           = 443028,
                celestialInfusion          = 1241059,
                chiBurst                   = 123986,
                chiTorpedo                 = 115008,
                detox                      = 218164,
                disable                    = 116095,
                envelopingMist             = 124682,
                explodingKeg               = 325153,
                fistsOfFury                = 113656,
                invokeChiJi,TheRedCrane    = 325197,
                invokeNiuzao,TheBlackOx    = 132578,
                invokeXuen,TheWhiteTiger   = 123904,
                invokeYulon,TheJadeSerpent = 322118,
                kegSmash                   = 121253,
                lifeCocoon                 = 116849,
                paralysis                  = 115078,
                purifyingBrew              = 119582,
                restoral                   = 388615,
                revival                    = 115310,
                ringOfPeace                = 116844,
                risingSunKick              = 107428,
                rushingJadeWind            = 116847,
                rushingWindKick            = 467307,
                sheilunsGift               = 399491,
                slicingWinds               = 1217413,
                songOfChiJi                = 198898,
                soothingMist               = 115175,
                spearHandStrike            = 116705,
                strikeOfTheWindlord        = 392983,
                summonBlackOxStatue        = 115315,
                summonJadeSerpentStatue    = 115313,
                thunderFocusTea            = 116680,
                tigersLust                 = 116841,
                transcendence              = 101643,
                whirlingDragonPunch        = 152175,
                zenith                     = 1249625,
            },
        },
    },
    PALADIN = {
        [65] = {
            abilities = {
                -- (none)
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                absolution           = 212056,
                beaconOfLight        = 53563,
                cleanse              = 4987,
                cleanseToxins        = 440013,
                divineProtection     = 498,
                holyLight            = 82326,
                judgment             = 275773,
                shieldOfTheRighteous = 415091,
            },
        },
        [70] = {
            abilities = {
                -- (none)
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                divineProtection = 403876,
                templarsVerdict  = 85256,
            },
        },
        Shared = {
            abilities = {
                blessingOfSummer       = 328620,
                crusaderStrike         = 35395,
                divineToll             = 304971,
                eyeOfTyr               = 209202,
                fireFromTheHeavens     = 58247,
                hammerOfWrath          = 24275,
                holyPrism              = 114871,
                holyShock              = 25912,
                intercession           = 391054,
                lightsHammer           = 114919,
                luminousCharger        = 55115,
                pillarOfLight          = 147974,
                redemption             = 7328,
                shieldOfTheRighteous   = 53600,
                tyrsDeliverance        = 200652,
                tyrsDeliverance_200654 = 200654,
                vanquishersHammer      = 328204,
                wakeOfAshes            = 205273,
                wingedVengeance        = 58244,
                wordOfGlory            = 85673,
            },
            buffs = {
                arcaneTorrent                = 155145,
                ashenHallow                  = 316958,
                contemplation                = 121183,
                crusaderAura                 = 32223,
                crusadersDirehorn            = 290608,
                divineShield                 = 642,
                earthenOrdinantsRamolith     = 453785,
                giftOfTheNaaru               = 59542,
                holyLightstrider             = 356802,
                retributionAura              = 183435,
                senseUndead                  = 5502,
                summonCharger                = 23214,
                summonDarkforgeRam           = 270562,
                summonDawnforgeRam           = 270564,
                summonExarchsElekk           = 73629,
                summonGreatExarchsElekk      = 73630,
                summonGreatSunwalkerKodo     = 69826,
                summonLightforgedRuinstrider = 363613,
                summonSunwalkerKodo          = 69820,
                summonThalassianCharger      = 34767,
                summonThalassianWarhorse     = 34769,
                summonWarhorse               = 13819,
            },
            debuffs = {
                handOfReckoning = 62124,
                jailersJudgment = 162056,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                ardentDefender         = 31850,
                auraMastery            = 31821,
                avengersShield         = 31935,
                avengingWrath          = 31884,
                beaconOfFaith          = 156910,
                beaconOfVirtue         = 200025,
                bladeOfJustice         = 184575,
                blessedHammer          = 204019,
                blessingOfFreedom      = 1044,
                blessingOfProtection   = 1022,
                blessingOfSacrifice    = 6940,
                blessingOfSpellwarding = 204018,
                blindingLight          = 115750,
                cleanseToxins          = 213644,
                divineSteed            = 190784,
                divineStorm            = 53385,
                divineToll             = 375576,
                eternalFlame           = 156322,
                executionSentence      = 343527,
                finalVerdict           = 383328,
                guardianOfAncientKings = 86659,
                hammerOfTheRighteous   = 53595,
                holyBulwark            = 432459,
                holyPrism              = 114165,
                holyShock              = 20473,
                layOnHands             = 633,
                lightOfDawn            = 85222,
                rebuke                 = 96231,
                riteOfAdjuration       = 433583,
                riteOfSanctification   = 433568,
                sentinel               = 389539,
                turnEvil               = 10326,
                wakeOfAshes            = 255937,
            },
        },
    },
    PRIEST = {
        Shared = {
            abilities = {
                heavens        = 112660,
                inspiredHymns  = 148074,
                mindgames      = 323673,
                resurrection   = 2006,
                sha            = 148071,
                shackleUndead  = 58251,
                shadow         = 107905,
                shadowyFriends = 126797,
                smite          = 585,
                theValkyr      = 126695,
                unholyNova     = 324724,
            },
            buffs = {
                arcaneTorrent      = 232633,
                ascension          = 161862,
                boonOfTheAscended  = 325013,
                faeGuardians       = 327661,
                giftOfTheNaaru     = 59544,
                powerWordFortitude = 21562,
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                angelicFeather    = 121536,
                apotheosis        = 200183,
                desperatePrayer   = 19236,
                dispelMagic       = 528,
                divineHymn        = 64843,
                dominateMind      = 205364,
                evangelism        = 472433,
                fade              = 586,
                guardianSpirit    = 47788,
                halo              = 120517,
                halo_120644       = 120644,
                holyFire          = 14914,
                holyNova          = 132157,
                holyWordChastise  = 88625,
                holyWordSanctify  = 34861,
                holyWordSerenity  = 2050,
                leapOfFaith       = 73325,
                massDispel        = 32375,
                mindBlast         = 8092,
                mindControl       = 605,
                painSuppression   = 33206,
                powerInfusion     = 10060,
                powerWordBarrier  = 62618,
                powerWordRadiance = 194509,
                prayerOfHealing   = 596,
                psychicScream     = 8122,
                purifyDisease     = 213634,
                shackleHorror     = 9484,
                shadowWordDeath   = 32379,
                shadowWordMadness = 335467,
                tentacleSlam      = 1227280,
                ultimatePenitence = 421453,
                voidTorrent       = 263165,
                voidform          = 228260,
            },
        },
    },
    ROGUE = {
        Shared = {
            abilities = {
                ambush            = 8676,
                disguise          = 63899,
                distract          = 1725,
                echoingReprimand  = 323547,
                flagellation      = 323654,
                kick              = 1766,
                pickLock          = 1804,
                serratedBoneSpike = 328547,
            },
            buffs = {
                arcaneTorrent   = 25046,
                crimsonVial     = 185311,
                cripplingPoison = 3408,
                detection       = 56814,
                feint           = 1966,
                giftOfTheNaaru  = 370626,
                instantPoison   = 315584,
                sliceAndDice    = 315496,
                sprint          = 2983,
            },
            debuffs = {
                kidneyShot = 408,
                sap        = 6770,
                sepsis     = 328305,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                adrenalineRush   = 13750,
                amplifyingPoison = 381664,
                atrophicPoison   = 381637,
                bladeRush        = 271877,
                blind            = 2094,
                cloakOfShadows   = 31224,
                crimsonTempest   = 1247227,
                deadlyPoison     = 2823,
                deathmark        = 360194,
                evasion          = 5277,
                gloomblade       = 200758,
                goremawsBite     = 426591,
                gouge            = 1776,
                keepItRolling    = 381989,
                killingSpree     = 51690,
                kingsbane        = 385627,
                numbingPoison    = 5761,
                preparation      = 1277933,
                shadowBlades     = 121471,
                shiv             = 5938,
                tricksOfTheTrade = 57934,
            },
        },
    },
    SHAMAN = {
        [262] = {
            abilities = {
                -- (none)
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                thunderstorm = 51490,
            },
        },
        [263] = {
            abilities = {
                -- (none)
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                feralLunge  = 196884,
                stormstrike = 17364,
            },
        },
        [264] = {
            abilities = {
                -- (none)
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                ancestralVision = 212048,
                cleanseSpirit   = 440012,
                healingWave     = 77472,
                purifySpirit    = 77130,
                waterShield     = 52127,
            },
        },
        Shared = {
            abilities = {
                ancestralSpirit    = 2008,
                astralRecall       = 556,
                chainHarvest       = 320674,
                earthbindTotem     = 2484,
                faeTransfusion     = 328923,
                healingSurge       = 8004,
                lightningBolt      = 188196,
                lingeringAncestors = 148080,
                primalStrike       = 73899,
                primordialWave     = 326059,
                spectralWolf       = 58261,
                spiritRaptors      = 148079,
                vesperTotem        = 324386,
            },
            buffs = {
                farSight        = 6196,
                ghostWolf       = 2645,
                giftOfTheNaaru  = 59547,
                lightningShield = 192106,
                waterWalking    = 546,
            },
            debuffs = {
                bloodlust  = 2825,
                heroism    = 32182,
                hex        = 210873,
                hex_211004 = 211004,
                hex_211010 = 211010,
                hex_211015 = 211015,
                hex_269352 = 269352,
                hex_277778 = 277778,
                hex_277784 = 277784,
                hex_309328 = 309328,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                ascendance           = 114050,
                ascendance_114051    = 114051,
                ascendance_114052    = 114052,
                astralShift          = 108271,
                capacitorTotem       = 192058,
                chainHeal            = 1064,
                chainLightning       = 188443,
                cleanseSpirit        = 51886,
                crashLightning       = 187874,
                doomWinds            = 384352,
                earthElemental       = 198103,
                earthShield          = 974,
                earthShock           = 8042,
                earthgrabTotem       = 51485,
                earthlivingWeapon    = 382021,
                earthquake           = 61882,
                earthquake_462620    = 462620,
                elementalBlast       = 117014,
                flametongueWeapon    = 318038,
                frostShock           = 196840,
                greaterPurge         = 378773,
                gustOfWind           = 192063,
                healingRain          = 73920,
                healingTideTotem     = 108280,
                hex                  = 51514,
                lavaBurst            = 51505,
                lavaLash             = 60103,
                naturesSwiftness     = 378081,
                poisonCleansingTotem = 383013,
                purge                = 370,
                riptide              = 61295,
                spiritLinkTotem      = 98008,
                spiritWalk           = 58875,
                spiritwalkersGrace   = 79206,
                stormkeeper          = 191634,
                sundering            = 197214,
                thunderstrikeWard    = 462757,
                totemicProjection    = 108287,
                tremorTotem          = 8143,
                unleashLife          = 73685,
                voltaicBlaze         = 470057,
                windRushTotem        = 192077,
                windShear            = 57994,
                windfuryWeapon       = 33757,
            },
        },
    },
    WARLOCK = {
        Shared = {
            abilities = {
                commandDemon             = 119898,
                createHealthstone        = 6201,
                createSoulwell           = 29893,
                crimsonBanish            = 63943,
                decimatingBolt           = 325289,
                eyeOfKilrogg             = 126,
                fear                     = 5782,
                felguard                 = 56285,
                impendingCatastrophe     = 321792,
                lordBanehollowsSoulstone = 416229,
                ritualOfDoom             = 342601,
                scouringTithe            = 312321,
                shadowBolt               = 686,
                soulstone                = 20707,
                soulwell                 = 58275,
                summonFelhunter          = 691,
                summonImp                = 688,
                summonSayaad             = 366222,
                summonVoidwalker         = 697,
            },
            buffs = {
                controlDemon      = 93375,
                dreadsteed        = 23161,
                felsteed          = 5784,
                giftOfTheNaaru    = 416250,
                ritualOfSummoning = 698,
                unendingBreath    = 5697,
                unendingResolve   = 104773,
            },
            debuffs = {
                corruption      = 146739,
                curseOfWeakness = 702,
                soulRot         = 325640,
                subjugateDemon  = 1098,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                agony               = 980,
                banish              = 710,
                blightOfTongues     = 1271802,
                burningRush         = 111400,
                callDreadstalkers   = 104316,
                cataclysm           = 152108,
                channelDemonfire    = 196447,
                chaosBolt           = 116858,
                conflagrate         = 17962,
                curseOfExhaustion   = 334275,
                curseOfTongues      = 1714,
                darkHarvest         = 1257052,
                darkPact            = 108416,
                demonicGateway      = 111771,
                felDomination       = 333889,
                grimoireFelRavager  = 1276467,
                grimoireImpLord     = 1276452,
                grimoireOfSacrifice = 108503,
                haunt               = 48181,
                havoc               = 80240,
                howlOfTerror        = 5484,
                implosion           = 196277,
                mortalCoil          = 6789,
                powerSiphon         = 264130,
                rainOfFire          = 5740,
                rainOfFire_1214467  = 1214467,
                seedOfCorruption    = 27243,
                shadowburn          = 17877,
                shadowfury          = 30283,
                soulFire            = 6353,
                soulburn            = 385899,
                summonDarkglare     = 205180,
                summonDemonicTyrant = 265187,
                summonDoomguard     = 1276672,
                summonFelguard      = 30146,
                summonInfernal      = 1122,
                unstableAffliction  = 1259790,
            },
        },
    },
    WARRIOR = {
        [65] = {
            abilities = {
                -- (none)
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                singleButtonAssistant = 1229376,
            },
        },
        [70] = {
            abilities = {
                -- (none)
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                singleButtonAssistant = 1229376,
            },
        },
        [71] = {
            abilities = {
                -- (none)
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                singleButtonAssistant = 1229376,
                sweepingStrikes       = 260708,
            },
        },
        [72] = {
            abilities = {
                -- (none)
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                execute               = 5308,
                singleButtonAssistant = 1229376,
                whirlwind             = 190411,
            },
        },
        [102] = {
            abilities = {
                -- (none)
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                singleButtonAssistant = 1229376,
            },
        },
        [105] = {
            abilities = {
                -- (none)
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                singleButtonAssistant = 1229376,
            },
        },
        [250] = {
            abilities = {
                -- (none)
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                singleButtonAssistant = 1229376,
            },
        },
        [251] = {
            abilities = {
                -- (none)
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                singleButtonAssistant = 1229376,
            },
        },
        [252] = {
            abilities = {
                -- (none)
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                singleButtonAssistant = 1229376,
            },
        },
        [253] = {
            abilities = {
                -- (none)
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                singleButtonAssistant = 1229376,
            },
        },
        [254] = {
            abilities = {
                -- (none)
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                singleButtonAssistant = 1229376,
            },
        },
        [262] = {
            abilities = {
                -- (none)
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                singleButtonAssistant = 1229376,
            },
        },
        [263] = {
            abilities = {
                -- (none)
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                singleButtonAssistant = 1229376,
            },
        },
        [264] = {
            abilities = {
                -- (none)
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                singleButtonAssistant = 1229376,
            },
        },
        [270] = {
            abilities = {
                -- (none)
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                singleButtonAssistant = 1229376,
            },
        },
        [1480] = {
            abilities = {
                -- (none)
            },
            buffs = {
                -- (none)
            },
            debuffs = {
                -- (none)
            },
            glyphs = {
                -- (none)
            },
            talents = {
                singleButtonAssistant = 1229376,
            },
        },
        Shared = {
            abilities = {
                ancientAftershock = 325886,
                attack            = 88163,
                blazingTrail      = 123780,
                burningAnger      = 112793,
                conquerorsBanner  = 324143,
                execute           = 163201,
                gushingWound      = 58279,
                hamstring         = 1715,
                hawkFeast         = 112792,
                heroicLeap        = 52174,
                heroicThrow       = 57755,
                mightyVictory     = 58281,
                pummel            = 6552,
                ragingBlow        = 85384,
                ragingBlow_96103  = 96103,
                shieldBlock       = 2565,
                shieldSlam        = 23922,
                slam              = 1464,
                spearOfBastion    = 307865,
                thunderStrike     = 68163,
                weaponmaster      = 148114,
                whirlwindOffHand  = 44949,
            },
            buffs = {
                arcaneTorrent  = 69179,
                berserkerRage  = 18499,
                charge         = 100,
                giftOfTheNaaru = 28880,
            },
            debuffs = {
                battleShout = 6673,
                taunt       = 355,
            },
            glyphs = {
                -- (none)
            },
            talents = {
                avatar              = 107574,
                battleStance        = 386164,
                berserkerShout      = 384100,
                berserkerStance     = 386196,
                bladestorm          = 227847,
                bloodthirst         = 23881,
                championsSpear      = 376079,
                cleave              = 845,
                colossusSmash       = 167105,
                defensiveStance     = 386208,
                demoralizingShout   = 1160,
                dieByTheSword       = 118038,
                disruptingShout     = 386071,
                enragedRegeneration = 184364,
                heroicLeap          = 6544,
                ignorePain          = 190456,
                ignorePain_1277297  = 1277297,
                impendingVictory    = 202168,
                interpose           = 1244088,
                intervene           = 3411,
                intimidatingShout   = 5246,
                mortalStrike        = 12294,
                odynsFury           = 385059,
                overpower           = 7384,
                piercingHowl        = 12323,
                ragingBlow          = 85288,
                rallyingCry         = 97462,
                rampage             = 184367,
                ravager             = 228920,
                recklessness        = 1719,
                rend                = 772,
                revenge             = 6572,
                shatteringThrow     = 64382,
                shieldCharge        = 385952,
                shieldWall          = 871,
                shockwave           = 46968,
                spellReflection     = 23920,
                stormBolt           = 107570,
                thunderClap         = 6343,
                wreckingThrow       = 384110,
            },
        },
    },
}
