-- --+--------------------+--
-- --|Am I Fighting Helya?|--
-- --+--------------------+--
-- function isBadRotationsHelya()
--   -- local objectCount = GetObjectCountBR() or 0
--   for i = 1,GetObjectCountBR() do
--     local name = ObjectName(ObjectWithIndex(i))
--     local object = ObjectWithIndex(i)
--     if name == "Helya" and GetObjectExists(object) then
--       coverThatHole()
--     else
--       end
--     end
--   end