local _, br = ...
br.lists.spells.ROGUE = br.lists.spells.ROGUE or {}
br.lists.spells.ROGUE.Shared = {
            abilities  = {
                ambush              = 8676,
                blind               = 2094,
                cheapShot           = 1833,
                cloakOfShadows      = 31224,
                combatReadiness     = 74001,  -- MoP defensive CD
                cripplingPoison     = 3408,
                deadlyPoison        = 2823,
                distract            = 1725,
                evasion             = 5277,
                eviscerate          = 2098,
                feint               = 1966,
                gouge               = 1776,
                instantPoison       = 6603,   -- MoP version
                kick                = 1766,
                kidneyShot          = 408,
                mindNumbingPoison   = 5761,   -- MoP version (previously Crippling in later expansions)
                paralyticPoison     = 108211, -- MoP poison
                pickLock            = 1804,
                pickPocket          = 921,
                redirect            = 73981,  -- MoP ability
                recuperate          = 73651,  -- MoP healing finisher
                sap                 = 6770,
                shroudOfConcealment = 114018, -- MoP group stealth
                sinisterStrike      = 1752,
                sliceAndDice        = 5171,
                sprint              = 2983,
                stealth             = 1784,
                throw               = 2764,   -- MoP version
                tricksOfTheTrade    = 57934,
                vanish              = 1856,
                woundPoison         = 8679,
            },
            buffs      = {
                cloakOfShadows      = 31224,
                combatReadiness     = 74001,
                cripplingPoison     = 3408,
                deadlyPoison        = 2823,
                evasion             = 5277,
                feint               = 1966,
                instantPoison       = 6603,
                mindNumbingPoison   = 5761,
                paralyticPoison     = 108211,
                recuperate          = 73651,
                shroudOfConcealment = 114018,
                sliceAndDice        = 5171,
                sprint              = 2983,
                stealth             = 1784,
                tricksOfTheTrade    = 57934,
                vanish              = 1856,
                woundPoison         = 8679,
            },
            debuffs    = {
                blind           = 2094,
                cheapShot       = 1833,
                cripplingPoison = 3408,
                garrote         = 703,
                gouge           = 1776,
                kidneyShot      = 408,
                mindNumbingPoison = 5761,
                paralyticPoison = 113952, -- Debuff version
                rupture         = 1943,
                sap             = 6770,
                woundPoison     = 8679,
            },
            glyphs     = {
                glyphOfAdrenalineRush  = 56803,
                glyphOfBlind           = 91299,
                glyphOfCloakOfShadows  = 63269,
                glyphOfExposedArmor    = 56805,
                glyphOfFanOfKnives     = 63254,
                glyphOfFeint           = 63257,
                glyphOfGarrote         = 56812,
                glyphOfGouge           = 56809,
                glyphOfKick            = 63252,
                glyphOfKillingSpree    = 63249,
                glyphOfSap             = 56798,
                glyphOfSprint          = 63250,
                glyphOfTricksOfTheTrade = 63256,
            },
            talents    = {
                -- Tier 2 (Level 30) - Shared across all Rogue specs
                deadlyThrow       = 26679,
                combatReadiness   = 74001,
            },
        }
