local _, br = ...
br.lists.spells.MAGE = br.lists.spells.MAGE or {}
br.lists.spells.MAGE.Shared = {
            abilities  = {
                alterTime               = 108978,
                arcaneBrilliance        = 1459,
                arcaneExplosion         = 1449,
                blink                   = 1953,
                blizzard                = 10,
                coneOfCold              = 120,
                conjureManaGem          = 759,
                conjureRefreshment      = 42955,
                conjureRefreshmentTable = 43987,
                counterspell            = 2139,
                deepFreeze              = 44572,
                evocation               = 12051,
                fireBlast               = 2136,
                flamestrike             = 2120,
                frostArmor              = 7302,
                frostfireBolt           = 44614,
                frostNova               = 122,
                iceBlock                = 45438,
                iceLance                = 30455,
                invisibility            = 66,
                manaBomb                = 125430,
                mageArmor               = 6117,
                mirrorImage             = 55342,
                moltenArmor             = 30482,
                polymorph               = 118,
                removeCurse             = 475,
                slowFall                = 130,
                spellsteal              = 30449,
                timeWarp                = 80353,
            },
            buffs      = {
                -- arcaneIntellect     = 1459,
                -- disciplinaryCommand = 327365,
                -- expandedPotential   = 327489,
                -- focusMagic          = 321358,
                -- freezingWinds       = 327364,
                -- iceBlock            = 45438,
                -- incantersFlow       = 1463,
                -- slowFall            = 130,
                -- slickIce            = 327509,
                -- runeOfPower         = 116014,
            },
            debuffs    = {
                -- frostNova        = 122,
                -- mirrorsOfTorment = 314793,
            },
            glyphs     = {

            },
            talents    = {
                -- incantersFlow = 1463,
                -- iceWard       = 205036,
                -- focusMagic    = 321358,
                -- ringOfFrost   = 113724,
                -- runeOfPower   = 116011,
                -- shimmer       = 212653,
                --unstableMagic               = 157976,
            },
        }
