name: Lint-PR

on:
    pull_request:
        types: ['opened', 'edited', 'reopened', 'synchronize']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lua-check:
    name: Lua Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    if: (github.actor != 'dependabot[bot]')

    steps:
    - name: Checkout source code
      uses: actions/checkout@v6.0.2

    # Optional step to run on only changed files
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v47.0.6
      with:
        since_last_remote_commit: true
        separator: "\n"
        files: |
          **.lua

    - name: Skip if no Lua files changed
      if: steps.changed-files.outputs.any_changed != 'true'
      run: echo "No Lua files changed, skipping linter." && exit 0

    - name: List changed files
      env:
        CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        echo "$CHANGED_FILES" | while IFS= read -r file; do
          [[ -n "$file" ]] && echo "$file was changed"
        done

    - name: Setup Lua
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: leafo/gh-actions-lua@35bcb06abec04ec87df82e08caa84d545348536e # v10
      with:
        luaVersion: "5.1"

    - name: Setup LuaRocks
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: leafo/gh-actions-luarocks@e65774a6386cb4f24e293dca7fc4ff89165b64c5 # v4

    - name: Install Luacheck
      if: steps.changed-files.outputs.any_changed == 'true'
      run: luarocks install luacheck

    - name: Run Luacheck for static analysis
      if: steps.changed-files.outputs.any_changed == 'true'
      env:
        CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      shell: bash
      continue-on-error: true
      run: |
        mapfile -t files <<< "$CHANGED_FILES"
        luacheck --codes --ranges --formatter JUnit -q "${files[@]}" > luacheck_${{ github.sha }}.xml || true

    - name: Upload results to workflow
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: actions/upload-artifact@v7.0.1
      with:
        name: luacheck_results.zip
        path: |
            luacheck_${{github.sha}}.xml
        if-no-files-found: warn

    # when using the regular GITHUB_TOKEN, the check-run created by this step will be assigned to a
    # random workflow in the GH UI. to prevent this, we can force the check-run to be created in a separate
    # check-suite, which is created automatically if we use the credentials of a GitHub App
    # Ref: https://github.com/EnricoMi/publish-unit-test-result-action/issues/181
    # Publishing: https://github.com/EnricoMi/publish-unit-test-result-action#publishing-test-results
    - name: Luacheck Report
      uses: EnricoMi/publish-unit-test-result-action@c950f6fb443cb5af20a377fd0dfaa78838901040 # v2
      if: steps.changed-files.outputs.any_changed == 'true' && github.actor != 'dependabot[bot]'
      with:
        files: |
            luacheck_${{github.sha}}.xml
        check_name: Luacheck Report
        comment_mode: always
        action_fail: true